#!/bin/sh
# rewrite accesses to arbitrary readings to use index.html
for f in build/es?-bundled; do
    cat >> $f/.htaccess <<EOF
RewriteEngine On
RewriteRule ^/[6789]{6}(,[6789]{6})*$ /index.html [QSA,L]
EOF
done