#!/bin/sh
# this is the rewrite required to make single page apps work, I hope
# rewrite accesses to arbitrary readings to use index.html
for f in build/es?-bundled; do
    cat >> $f/.htaccess <<EOF
    RewriteEngine on

    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]
    RewriteRule ^(.*) /index.html [NC,L]
EOF
done

