export class ChangesText {
static get name() { return "wilhelm-google" }
static get edition() { return "text-wilhelm-google.xml" }
static get version() { return "2018-06-04-17-39-59" }
static get changes() { return [
  {
    "number" : "1",
    "name-interpretation" : "The creative",
    "judgment" : "The creative works sublime success,\n promoted by perseverance.",
    "line-1" : "Initially a nine means:\n Masked Dragon, do not act!",
    "line-2" : "Nine in second place means:\n Dragon appearing on the field.\n It is encouraging to see the big man.",
    "line-3" : "Nine in third place means:\n The noble is creatively active throughout the day.\n He is still full of anxiety in the evening.\n Danger. No blemish.",
    "line-4" : "Nine in fourth place means:\n Fluctuating upswing over the depths.\n No blemish.",
    "line-5" : "Nine in fifth place means:\n Flying dragon in the sky.\n It is encouraging to see the big man.",
    "line-6" : "Above a nine means:\n Haughty Dragon will have to repent.",
    "line-7" : "When a lot of nines appear, it means:\n A flock of dragons without a head appears. Salvation! A flock of dragons without a head appears. Salvation!",
  },
  {
    "number" : "2",
    "name-interpretation" : "The Receptive",
    "judgment" : "The Receptive is sublime,\n fostered by the persistence of a mare.\n If the noble has something to do and wants to go ahead,\n he goes astray; but if he follows, he finds guidance.\n It is to find friends in the west and in the south, to be friends\n encouraging in the east and north.\n Peaceful persistence brings salvation.",
    "line-1" : "Initially a six means:\n If you step on hoop, then the solid ice is approaching.",
    "line-2" : "Six in second place means:\n Straight, right-angled, big.\n Without intention, nothing remains unsaid.",
    "line-3" : "Six in third place means:\n Hidden lines; one is able to persist.\n If you follow a king's service,\n do not seek works, but complete!",
    "line-4" : "Six in fourth place means:\n Bound bag. No blemish; no praise.",
    "line-5" : "Six in fifth place means:\n Yellow undergarment brings sublime salvation.",
    "line-6" : "Above a six means:\n Dragons fight on the Anger.\n Her blood is black and yellow.",
    "line-7" : "When all sixes appear, this means:\n Promoting is persevering persistence. Promoting is persevering persistence.",
  },
  {
    "number" : "3",
    "name-interpretation" : "The initial difficulty",
    "judgment" : "The initial difficulty is sublime.\n Encouraging through perseverance.\n You should not do anything.\n It is encouraging to use assistants.",
    "line-1" : "Initially a nine means:\n Hesitation and inhibition.\n It is encouraging to persist.\n It is encouraging to use assistants.",
    "line-2" : "Six in second place means:\n Difficulties pile up.\n Horse and cart are parting.\n Not a robber he is,\n wants to get free to the deadline.\n The girl is chaste, does not promise.\n Ten years, then she promises.",
    "line-3" : "Six in third place means:\n Who hunts the deer without a forester,\n who gets lost only in the forest.\n The noble understands the signs of the times\n and prefers to leave.\n Continuing brings shame.",
    "line-4" : "Six in the fourth place means:\n Horse and car separate.\n Looking for union.\n Going to bring salvation.\n Everything works well.",
    "line-5" : "Nine in fifth place means:\n Difficulty in blessing.\n Little perseverance brings salvation,\n great perseverance brings disaster.",
    "line-6" : "Above a six means:\n Horse and cart are parting.\n Bloody tears spill out.",
  },
  {
    "number" : "4",
    "name-interpretation" : "The Youthful Folly",
    "judgment" : "Youthful folly has succeeded.\n Not I look for the young fool,\n the young gate is looking for me.\n At the first oracle I give information.\n If he asks two or three times, that's harassment.\n If he harasses, I give no information.\n Promoting is perseverance.",
    "line-1" : "Initially a six means:\n To develop the fool,\n it is helpful to breed the human.\n You should take off the shackles.\n To continue this way brings shame.",
    "line-2" : "Nine in second place means:\n The gates endure in mildness, brings salvation.\n Knowing the women brings salvation.\n The son has grown up to the household.",
    "line-3" : "Six in third place means:\n Do not take a girl who\n sees a brazen man\n and does not keep possession.\n Nothing is promotional.",
    "line-4" : "Six in fourth place means:\n Limited youthfulness brings shame.",
    "line-5" : "Six in fifth place means:\n Childish folly brings salvation.",
    "line-6" : "Nine at the top means:\n In punishing folly, it is not encouraging\n to commit abuses.\n Promoting is only to ward off attacks.",
  },
  {
    "number" : "5",
    "name-interpretation" : "Waiting, (nutrition)",
    "judgment" : "Waiting.\n If you are true, you have light and success.\n Perseverance brings salvation.\n It is encouraging to cross the big water.",
    "line-1" : "At first a nine means:\n Waiting on the Anger.\n It is encouraging to stay in the end.\n No blemish.",
    "line-2" : "Nine in second place means:\n Waiting on the sand.\n There is a little talk.\n The end brings salvation.",
    "line-3" : "Nine in third place means:\n Waiting in the mud\n causes the enemy to come.",
    "line-4" : "Six in fourth place means:\n Waiting in the blood.\n Out of the hole.",
    "line-5" : "Nine in fifth place means:\n Waiting with wine and food.\n Perseverance brings salvation.",
    "line-6" : "Above a six means:\n You get into the hole.\n There are three unwelcome guests.\n Honor them, then in the end salvation comes.",
  },
  {
    "number" : "6",
    "name-interpretation" : "The Dispute",
    "judgment" : "The Dispute: You are true and inhibited.\n Careful pausing half way brings salvation.\n To finish brings disaster.\n It is encouraging to see the big man.\n It is not beneficial to cross the big water.",
    "line-1" : "Initially a six means:\n If you do not immortalize the thing,\n then there is a little talk.\n In the end comes salvation.",
    "line-2" : "Nine in second place means:\n You can not argue, go home and avoid.\n The people of his city, three hundred houses,\n remain free of guilt.",
    "line-3" : "Six in the third place means:\n Nourishing oneself from old virtue gives perseverance.\n Danger, in the end comes salvation.\n If you follow a king's service,\n do not seek works.",
    "line-4" : "Nine in fourth place means:\n One can not argue,\n turn around and adhere to the skill,\n change and find peace in perseverance.\n Salvation!",
    "line-5" : "Nine in fifth place means:\n Arguing before him brings sublime salvation.",
    "line-6" : "Nine at the top means:\n If you also get a leather belt, for example,\n at the end of a morning you will be torn from it three times.",
  },
  {
    "number" : "7",
    "name-interpretation" : "The Army",
    "judgment" : "The army needs perseverance\n and a strong man.\n Salvation without blemish.",
    "line-1" : "Initially a six means:\n An army must take off after the order.\n If that is not good, disaster threatens.",
    "line-2" : "Nine in second place means:\n In the midst of the army!\n Salvation! No blemish!\n The king gives triple award.",
    "line-3" : "Six in third place means:\n The army leads corpses in the car. Mischief!",
    "line-4" : "Six in fourth place means:\n The army withdraws. No blemish.",
    "line-5" : "Six in fifth place means:\n In the field is a game. It is beneficial to catch it.\n Without blemish.\n The elder leads the army.\n The younger man drives corpses,\n but perseverance brings disaster.",
    "line-6" : "Above a six means:\n The great prince issues orders,implants\n founds states,families.\n You should not use common people.",
  },
  {
    "number" : "8",
    "name-interpretation" : "Holding together",
    "judgment" : "Holding together brings salvation.\n Recreate the oracle,\n whether you have sublimity, duration, and perseverance;\n then there is no blemish.\n The insecure people come gradually.\n Who comes too late, has mischief.",
    "line-1" : "Initially a six means:\n Keep true and faithful to him: this is no blemish.\n Truth like a full tone bowl:\n so salvation comes from the outside.",
    "line-2" : "Six in second place means:\n Hold to him inside. Perseverance brings salvation.",
    "line-3" : "Six in third place means:\n You are holding together with people who\n are not the right ones.",
    "line-4" : "Six in fourth place means:\n Also outwardly, stick to him. Perseverance brings salvation.",
    "line-5" : "Nine in fifth place means:\n Revelation of holding together.\n The king can only drive from three sides in the hunt\n and renounces the game that turns in front.\n The citizens do not need the warning. Salvation!",
    "line-6" : "Above a six means:\n He finds no head to hold together. Mischief.",
  },
  {
    "number" : "9",
    "name-interpretation" : "The Little Taming Power of the",
    "judgment" : "Little Taming Power has succeeded.\n Dense clouds, no rain from our western area.",
    "line-1" : "At first a nine means:\n Return on the way. How would that be a blemish! Salvation!",
    "line-2" : "Nine in second place means:\n Lets go along to the return. Salvation!",
    "line-3" : "Nine in third place means:\n The spokes jump off the car.\n Man and woman turn their eyes.",
    "line-4" : "Six in the fourth place means:\n If you are true, blood fades and gives way to fear.\n No blemish.",
    "line-5" : "Nine in fifth place means:\n If you are true and loyal,\n you are rich in your neighbor.",
    "line-6" : "Above a nine means:\n It comes to the rain, it comes to rest.\n This is due to the lasting effect of the character.\n The woman is endangered by perseverance.\n The moon is almost full. If the noble continues,\n then disaster comes.",
  },
  {
    "number" : "10",
    "name-interpretation" : "The occurrence",
    "judgment" : "Occur on the tiger's tail.\n He does not bite man. Success.",
    "line-1" : "At first a nine means:\n Simple appearance. Progression without blemish.",
    "line-2" : "Nine in second place means:\n Appearance on plain, level course.\n A dark man's persistence brings salvation.",
    "line-3" : "Six in third place means:\n One-eyed one can see, a lame one can occur.\n He kicks on the tiger's cock. He bites the human.\n Mischief!\n A warrior acts like that for his great prince.",
    "line-4" : "Nine in fourth place means:\n He steps on the tiger's tail.\n Caution and cautiousness finally leads to salvation.",
    "line-5" : "Nine in fifth place means:\n Determination.\n Perseverance in awareness of danger.",
    "line-6" : "Ninetop means:\n At thelook at your appearance and check the favorable signs.\n If everything is perfect, then there will be sublime salvation.",
  },
  {
    "number" : "11",
    "name-interpretation" : "Peace",
    "judgment" : "Peace. The little one goes, the big one comes here.\n Salvation! Success!",
    "line-1" : "In the beginning a nine means:\n If one pulls out Bandgras, the lawn goes with it.\n Each in his own way. Things bring salvation.",
    "line-2" : "Nine in second place means:\n To carry the uneducated in clemency,\n determined to cross the river,\n not to neglect the distance, to disregard\n the comrades:\n thus one may manage to walk in the middle.",
    "line-3" : "Nine in third place means:\n No plane that does not follow a slope,\n no entrance that does not follow the return.\n Without blemish is who persistently remains in danger.\n Do not complain about this truth,\n enjoy the happiness that you still have.",
    "line-4" : "Six in the fourth place means:\n He flutters down, not thumping on wealth,\n along with his neighbor, innocent and truthful.",
    "line-5" : "Six in fifth place means:\n The ruler I gives his daughter into marriage.\n This brings blessing and sublime salvation.",
    "line-6" : "Above a six means:\n The wall falls back into the ditch.\n Now need no armies.\n In your own city, announce your orders.\n Perseverance brings shame.",
  },
  {
    "number" : "12",
    "name-interpretation" : "The stagnation",
    "judgment" : "The stagnation.\n Bad people are not supportive\n of the perseverance of the noble.\n The big one goes, the little one comes here.",
    "line-1" : "At the beginning a six means:\n If one pulls out bandgrass, then the lawn goes along.\n Each in hisway.\n ownPerseverance brings healing and success.",
    "line-2" : "Six in second place means:\n They carry and tolerate,\n that means for the common salvation.\n The stoppage serves the great man to succeed.",
    "line-3" : "Six in third place means:\n You are ashamed.",
    "line-4" : "Nine in the fourth place means:\n Whoever acts on the command of the Supreme, remains without blemish.\n The like-minded people enjoy the blessing.",
    "line-5" : "Nine in fifth place means:\n The stagnation eases. The great man Heil!\n &quot;If it misses, if it misses,&quot; heshrubs\n ties it to a bunch of mulberry.",
    "line-6" : "Above a nine means:\n The stoppage stops.\n First stagnation, then salvation!",
  },
  {
    "number" : "13",
    "name-interpretation" : "Community with people",
    "judgment" : "Community with people outdoors: succeed.\n It is encouraging to cross the big water.\n Promoting is the noble perseverance.",
    "line-1" : "Initially a nine means:\n Fellowship with people in the gates. No blemish.",
    "line-2" : "Six in second place means:\n Fellowship with people in the clan: shame.",
    "line-3" : "Nine in third place means:\n Hiding weapons in the thicket,\n climbs on the high hill in front of it.\n He does not rise for three years.",
    "line-4" : "Nine in fourth place means:\n He climbs his wall, he can not attack. Salvation!",
    "line-5" : "Nine in fifth place means:\n The common people first cry and complain,\n but afterwards they laugh.\n After big battles they manage to meet each other.",
    "line-6" : "Above a nine means:\n Fellowship with people on the Anger: no remorse.",
  },
  {
    "number" : "14",
    "name-interpretation" : "The possession of great",
    "judgment" : "The possession of great: sublime success!",
    "line-1" : "At first a nine means:\n No relation to harmful, that is not a blemish.\n If youaware of the difficulty,\n remainyou remain without blemish.",
    "line-2" : "Nine in second place means:\n A big car for loading.\n You may do something. No blemish.",
    "line-3" : "Nine in third place means:\n A prince brings it to the Son of Heaven.\n A little person can not do that.",
    "line-4" : "Nine in fourth place means:\n He makes a difference\n between himself and his neighbor.\n No blemish.",
    "line-5" : "Six in fifth place means:\n Whose truth is accessible and\n yet worthy, has salvation.",
    "line-6" : "Above a nine means:\n From the sky he is blessed, salvation!\n Nothing that is not promotional.",
  },
  {
    "number" : "15",
    "name-interpretation" : "Modesty",
    "judgment" : "Modesty creates success.\n The noble brings to an end.",
    "line-1" : "Initially a six means:\n A modest-modest noble\n may cross the great water. Salvation!",
    "line-2" : "Six in second place means:\n Expressing modesty. Perseverance brings salvation.",
    "line-3" : "Nine in third place means:\n A meritorious-modest noble comes to an end.\n Salvation!",
    "line-4" : "Six in fourth place means:\n Nothing that does not promote\n modesty in movement.",
    "line-5" : "Six in fifth place means:\n Do not insist on wealth to your neighbor.\n It is encouraging to attack by force.\n Nothing that would not be supportive.",
    "line-6" : "Above a six means:\n Expressing modesty.\n It is encouraging to march armies to punish\n their own city and their own country.",
  },
  {
    "number" : "16",
    "name-interpretation" : "Enthusiasm",
    "judgment" : "Enthusiasm. It is\n encouraging to employ assistants and march armies.",
    "line-1" : "Initially a six means:\n Enthusiasm that expresses brings disaster.",
    "line-2" : "Six in second place means:\n Solid as a stone. Not a whole day.\n Perseverance brings salvation.",
    "line-3" : "Six in the third place means:\n Upward looking enthusiasm creates regret.\n Hesitation brings repentance.",
    "line-4" : "Nine in fourth place means:\n The origin of enthusiasm. He achieves great things.\n Do not doubt!\n The friends flock around you\n like a hair clip.",
    "line-5" : "Six in fifth place means:\n Persistently sick and yet never dies.",
    "line-6" : "Above a six means:\n Blinded enthusiasm.\n But if you come to the completion of the change,\n so that's no blemish.",
  },
  {
    "number" : "17",
    "name-interpretation" : "The Succession",
    "judgment" : "Succession has sublime success.\n Promoting is perseverance. No blemish.",
    "line-1" : "Initially a nine means:\n The authoritative changes. Perseverance brings salvation.\n Going out the door in traffic creates works.",
    "line-2" : "Six in second place means:\n If you depend on the little boy,\n you lose the strong man.",
    "line-3" : "Six in third place means:\n If you depend on the strong man,\n you lose the little boy.\n By succession you can find what you are looking for.\n It is encouraging to persist.",
    "line-4" : "Nine in fourth place means:\n Succession creates success. Perseverance brings disaster.\n Walking with truthfulness on the way\n brings clarity.\n How could that be a blemish?",
    "line-5" : "Nine in fifth place means:\n True in good. Salvation!",
    "line-6" : "Above a six means:\n He finds solid attachment\n and is bound to it.\n The king introduces him to the Westberg.",
  },
  {
    "number" : "18",
    "name-interpretation" : "Work on the Corrupt",
    "judgment" : "The work on the corrupt has sublime success.\n It is encouraging to cross the big water.\n Three days before the starting point, three days\n after the starting point.",
    "line-1" : "Initially a six means:\n Correcting the father's depravity.\n If a son is there, there\n will be no blemish on his deceased father.\n Danger. Finally, salvation.",
    "line-2" : "Nine in second place means:\n Bringing the mother spoiled away.\n One must not be too persistent.",
    "line-3" : "Nine in third place means:\n To correct the one corrupted by the father.\n There will be a little regret. No big flaw.",
    "line-4" : "Six in fourth place means:\n To endure the father's depravity.\n When making progress you will see shame.",
    "line-5" : "Six in fifth place means:\n Correction of the one corrupted by the father.\n One finds praise.",
    "line-6" : "Above a nine means:\n Does not serve kings and princes.\n Put higher goals.",
  },
  {
    "number" : "19",
    "name-interpretation" : "Approach",
    "judgment" : "Approach has sublime success.\n Promoting is perseverance.\n If the eighth month comes, then there is mischief.",
    "line-1" : "Initially a nine means:\n Common approach. Perseverance brings salvation.",
    "line-2" : "Nine in second place means:\n Common approach. Salvation! Everything is promotional.",
    "line-3" : "Six in third place means:\n Comfortable approach. Nothing that would be supportive.\n If you reach sadness about it, you will be without blemish.",
    "line-4" : "Six in fourth place means:\n Perfect approach. No blemish.",
    "line-5" : "Six in fifth place means:\n Way approach. That's right for\n a great prince. Salvation!",
    "line-6" : "Above a six means:\n Great-hearted approach. Salvation. No blemish.",
  },
  {
    "number" : "20",
    "name-interpretation" : "The Contemplation, (the Sight)",
    "judgment" : "The Contemplation.\n The washing has been done, but not yet the offering.\n They look up at him with confidence.",
    "line-1" : "Initially a six means:\n Boyish viewing.\n For a small person no blemish.\n Shaming for a noble.",
    "line-2" : "Six in second place means:\n Looking through the door column.\n Promoting is the perseverance of a woman.",
    "line-3" : "Six in the third place means:\n Contemplation of my life decides\n on progress or retreat.",
    "line-4" : "Six in the fourth place means:\n Contemplation of the light of the kingdom.\n It is encouraging to act as a guest of a king.",
    "line-5" : "Nine in fifth place means:\n Contemplation of my life.\n The noble is without blemish.",
    "line-6" : "Above a nine means:\n Contemplation of his life.\n The noble is without blemish.",
  },
  {
    "number" : "21",
    "name-interpretation" : "The biting through",
    "judgment" : "The biting has succeeded.\n It is encouraging to make court.",
    "line-1" : "Initially a nine means:\n Put your feet in the block so that your toes disappear.\n No blemish.",
    "line-2" : "Six in second place means:\n Biting through soft flesh that the nose disappears.\n No blemish.",
    "line-3" : "Six in third place means:\n Bite on old jerky meat and find poisonous.\n Little embarrassment. No blemish.",
    "line-4" : "Nine in fourth place means:\n Bites on dried cartilage meat.\n Receives metal arrows.\n It is\n encouraging to be aware of the difficulties and to persist.\n Salvation!",
    "line-5" : "Six in fifth place means:\n Bites on dried muscle meat.\n Receives yellow gold.\n To be perseveringly aware of the danger. No blemish.",
    "line-6" : "Ninetop means:\n At thePut your neck in the wooden collar so\n that your ears disappear.\n Mischief!",
  },
  {
    "number" : "22",
    "name-interpretation" : "Grace",
    "judgment" : "Grace succeeds.\n On a small scale it is helpful to do something.",
    "line-1" : "At first a nine means:\n Gracefully turns his toes, leaves the car and leaves.",
    "line-2" : "Six in second place means:\n Make his beard graceful.",
    "line-3" : "Nine in third place means:\n Graceful and humid.\n Constant persistence brings salvation.",
    "line-4" : "Six in fourth place means:\n Grace or simplicity?\n A white horse comes flying like this:\n not robber he is free to deadline.",
    "line-5" : "Six in fifth place means:\n Grace in hills and gardens.\n The silk bundle is poor and small.\n Shame, but finally salvation.",
    "line-6" : "Above a nine means:\n Simple grace.\n No blemish.",
  },
  {
    "number" : "23",
    "name-interpretation" : "The fragmentation",
    "judgment" : "The fragmentation. Not promotional is where to go.",
    "line-1" : "Initially a six means:\n The bed is splintered on the leg.\n The persistent ones are destroyed. Mischief.",
    "line-2" : "Six in second place means:\n The bed is shattered on the edge.\n The persistent ones are destroyed. Mischief.",
    "line-3" : "Six in third place means:\n He splinters with you. No blemish.",
    "line-4" : "Six in fourth place means:\n The bed is shattered to the skin. Mischief.",
    "line-5" : "Six in fifth place means:\n A train of fish. By the palace ladies comes favor.\n Everything is beneficial.",
    "line-6" : "Nine at the top means:\n A big fruit is still there.\n The noble receives a car.\n The house splinters the house.",
  },
  {
    "number" : "24",
    "name-interpretation" : "The return, (the turning time)",
    "judgment" : "The return. Success.\n Output and input without error.\n Friends come without blemish.\n The way goes back and forth.\n On the seventh day comes the return.\n It is encouraging to have where you go.",
    "line-1" : "At first a nine means:\n Return from a short distance.\n There is no need for remorse.\n Great salvation!",
    "line-2" : "Six in second place means:\n Quiet return. Salvation!",
    "line-3" : "Six in third place means:\n Multiple recurrence. Danger. No blemish.",
    "line-4" : "Six in the fourth place means:\n Walking in the middle of the other\n one returns alone.",
    "line-5" : "Six in fifth place means:\n Generous return. No mercy.",
    "line-6" : "Above a six means:\n Missing the return. Mischief.\n Misfortune from outside and inside.\n If one lets such armies march,\n one will finally suffer a great defeat,\n so that it is disastrous for the sovereign.\n For ten years you are no longer able to attack.",
  },
  {
    "number" : "25",
    "name-interpretation" : "Innocence, (the unexpected)",
    "judgment" : "Innocence. Sublime success.\n Promoting is perseverance.\n If someone is, he has misfortune,\n wrongand it is not encouraging to do anything.",
    "line-1" : "At first a nine means:\n Innocent change brings salvation!",
    "line-2" : "Six in second place means:\n If you do not think about harvesting while plowing\n and not about using the field when digging,\n then it is helpful to do something.",
    "line-3" : "Six in third place means:\n Innocent Misfortune:\n The cow that was tailed by someone\n is the wanderer's profit, the citizen's loss.",
    "line-4" : "Nine in the fourth place means:\n Whoever can be persistent, stays without blemish.",
    "line-5" : "Nine in fifth place means:\n In the case of no-fault illness do not use any remedy.\n It will be good by itself.",
    "line-6" : "Above a nine means:\n Innocent action brings misfortune.\n Nothing is promotional.",
  },
  {
    "number" : "26",
    "name-interpretation" : "The Great Taming Power",
    "judgment" : "Of The Great Taming Power.\n Promoting is perseverance.\n Not eating at home brings salvation.\n It is encouraging to cross the big water.",
    "line-1" : "At first a nine means:\n There is danger there. It is encouraging to stand down.",
    "line-2" : "Nine in second place means:\n The axle is removed from the car.",
    "line-3" : "Nine in third place means:\n One good horse following another.\n Promoting is awareness of danger and perseverance.\n Daily practice in car driving and weapons protection.\n It is encouraging to have where you go.",
    "line-4" : "Six in fourth place means:\n The protection board of a young bull.\n Great salvation!",
    "line-5" : "Six in fifth place means:\n A blundered boar tooth. Salvation!",
    "line-6" : "Above a nine means:\n One attains the heavenly way. Success.",
  },
  {
    "number" : "27",
    "name-interpretation" : "The corners of the mouth, (the diet)",
    "judgment" : "The corners of the mouth. Perseverance brings salvation.\n Look at the diet and what one seeks\n to fill his mouth with.",
    "line-1" : "At first a nine means:\n You drive your magicyour\n turtle and look at me with drooping corners ofmouth.\n Mischief!",
    "line-2" : "Six in second place means:\n After the summit turn to nutrition.\n To deviate from the roadfrom the hill\n to seek food:\n if you continue to do so, it brings disaster.",
    "line-3" : "Six in third place means:\n Deviating from the diet.\n Perseverance brings disaster.\n Ten years do not act accordingly. Nothing is promotional.",
    "line-4" : "Six in fourth place means:\n Turning to the summit for nutrition brings salvation.\n Looking around with sharp eyes like a tiger\n in insatiable desire. No blemish.",
    "line-5" : "Six in fifth place means:\n Departure from the path.\n Staying in perseverance brings salvation.\n You should not cross the big water.",
    "line-6" : "Above a nine means:\n The source of nutrition.\n Consciousness of danger brings salvation.\n It is encouraging to cross the big water.",
  },
  {
    "number" : "28",
    "name-interpretation" : "The Great Overweight",
    "judgment" : "Of The Great Overweight. The ridge beam bends through.\n It is encouraging to have where you go. Success.",
    "line-1" : "Initially a six means:\n Underlay with white reed grass.\n No blemish.",
    "line-2" : "Nine in second place means:\n A dry cottonwood tree drives a root shoot.\n An older man gets a young wife.\n Everything is promotional.",
    "line-3" : "Nine in third place means:\n The ridge beam bends through. Mischief.",
    "line-4" : "Nine in fourth place means:\n The ridge-beam is supported. Salvation.\n If ulterior motives are there, it is shameful.",
    "line-5" : "Nine in fifth place means:\n A dry poplar is blossoming.\n An older woman gets a husband.\n No blemish. No praise.",
    "line-6" : "Above a six means:\n You have to go through the water.\n It goes over the top.\n Mischief. No blemish.",
  },
  {
    "number" : "29",
    "name-interpretation" : "The Abyssal, the Water",
    "judgment" : "The Repeated Abyssal.\n If you are true, then you have success in the heart,\n and what you do succeed.",
    "line-1" : "Initially a six means:\n Repetition of the abysmal.\n You get into a hole in the abyss. Mischief.",
    "line-2" : "Nine in second place means:\n The abyss is in danger.\n One should strive only to achieve something small.",
    "line-3" : "Six in third place means:\n Forward and backward, abyss over abyss.\n In such danger stop first,\n otherwise you come in the abyss in a hole.\n Do not act like that.",
    "line-4" : "Six in fourth place means:\n A jug of wine, a rice bowl as an encore, a clay bowl,\n simply poured into the window.\n That's not a blemish.",
    "line-5" : "Nine in fifth place means:\n The abyss is not crowded,\n is only filled to the brim.\n No blemish.",
    "line-6" : "Above a six means:\n Bound with ropes and ropes,\n enclosed between thorn-hewn prison walls;\n For three years you can not cope.\n Mischief!",
  },
  {
    "number" : "30",
    "name-interpretation" : "The sticking, the fire",
    "judgment" : "The sticking. Promoting is perseverance.\n She brings success. Caring for the cow brings salvation.",
    "line-1" : "At first a nine means:\n The footsteps criss-cross.\n If you are serious about it: no blemish.",
    "line-2" : "Six in second place means:\n Yellow glow. Sublime salvation.",
    "line-3" : "Nine in third place means:\n In the light of the setting sun,\n people either hit the pot and sing,\n or they sigh loudly about the approaching old age.\n Mischief.",
    "line-4" : "Nine in the fourth place means:\n Suddenly his coming;\n it burns, dies, is thrown away.",
    "line-5" : "Six in fifth place means:\n Crying in torrents, sighing and plaintive. Salvation!",
    "line-6" : "Above a nine means:\n The king uses him to take off and chastise.\n It is best then to kill the heads\n and capture the followers. No blemish.",
  },
  {
    "number" : "31",
    "name-interpretation" : "Action, (advertising)",
    "judgment" : "Action. Success.\n Promoting is perseverance.\n Taking a girl brings salvation.",
    "line-1" : "Initially a six means:\n The effect is expressed in the big toe.",
    "line-2" : "Six in second place means:\n The effect is expressed in the calves. Mischief!\n Lingering brings salvation!",
    "line-3" : "Nine in third place means:\n The impact is expressed in the thighs.\n Stick to what follows him.\n Carry on is shameful.",
    "line-4" : "Nine in the fourth place means:\n Perseverance brings salvation! Repentance disappears.\n If you think excitedly back and forth,\n then only the friends follow,\n to whom one directs conscious thoughts.",
    "line-5" : "Nine in fifth place means:\n The impact manifests itself in the neck.\n No mercy.",
    "line-6" : "Above a six means:\n The impact manifests itself in jaw,\n cheeks and tongue.",
  },
  {
    "number" : "32",
    "name-interpretation" : "The duration",
    "judgment" : "Succeed. No blemish.\n Promoting is perseverance.\n It is beneficial to have where you go.",
    "line-1" : "Initially a six means:\n Wanting too fast duration brings persistent mischief.\n Nothing that would be supportive.",
    "line-2" : "Nine in second place means:\n Regret disappears.",
    "line-3" : "Nine in third place means:\n To your If you do not give durationcharacter,\n you offer shame.\n Persistent shame.",
    "line-4" : "Nine in fourth place means:\n There is no game in the field.",
    "line-5" : "Six in fifth place means:\n To give duration to his character through perseverance,\n that is for a woman of salvation, for a man of mischief.",
    "line-6" : "Above a six means:\n Restlessness as a permanent state brings disaster.",
  },
  {
    "number" : "33",
    "name-interpretation" : "The Retreat",
    "judgment" : "The Retreat. Success.\n In the small is promoting perseverance.",
    "line-1" : "Initially a six means:\n When retreating at the tail: that is dangerous.\n You can not do something.",
    "line-2" : "Six in second place means:\n He holds him tight with yellow oxhide.\n Nobody can tear it off.",
    "line-3" : "Nine in third place means:\n That the detained retreat is embarrassing and dangerous.\n To keep the people as slaves and maids brings salvation.",
    "line-4" : "Nine in the fourth place means:\n Voluntary retreat brings the noble salvation,\n the common decline.",
    "line-5" : "Nine in fifth place means:\n Friendly retreat. Perseverance brings salvation.",
    "line-6" : "Nine at the top means:\n A happy retreat. Everything is promotional.",
  },
  {
    "number" : "34",
    "name-interpretation" : "The Great Power",
    "judgment" : "Of The Great Power. Promoting is perseverance.",
    "line-1" : "At first a nine means:\n Power in the toes.\n Doing away brings disaster.\n That is certainly true.",
    "line-2" : "Nine in second place means:\n Perseverance brings salvation.",
    "line-3" : "Nine in third place means:\n The common works through power, the noble does not work that way.\n Dismantling is dangerous.\n A goat bumps against a hedge\n and entangles its horns.",
    "line-4" : "Nine in the fourth place means:\n Perseverance brings salvation.\n Repentance disappears.\n The hedge opens, there is no involvement.\n Power rests on the axis of a big car.",
    "line-5" : "Six in fifth place means:\n Loses the goat with ease.\n No mercy.",
    "line-6" : "Above a six means:\n A goat bumps against a hedge:\n he can not go back, he can not move forward.\n Nothing is promotional.\n If one notices the difficulty, then salvation brings.",
  },
  {
    "number" : "35",
    "name-interpretation" : "Progress",
    "judgment" : "Progress:\n The strong prince is honored by horses in large numbers.\n He is received three times in one day.",
    "line-1" : "Initially a six means:\n Progressive, but rejected.\n Perseverance brings salvation.\n If you do not trust, you stay calm.\n No mistake.",
    "line-2" : "Six in second place means:\n Progressing, but in mourning:\n perseverance brings salvation.\n One then gets great luck from his ancestress.",
    "line-3" : "Six in third place means:\n Everyone agrees. Repentance disappears.",
    "line-4" : "Nine in fourth place means:\n Progress like a hamster.\n Perseverance brings danger.",
    "line-5" : "Six in fifth place means:\n Regret disappears.\n Profit and loss do not take to heart.\n Businesses bring salvation.\n Everything is promotional.",
    "line-6" : "Ninetop means:\n At theYou can only proceed with the horns in\n order to punish your own territory.\n Consciousness of danger brings salvation.\n No blemish.\n Perseverance brings shame.",
  },
  {
    "number" : "36",
    "name-interpretation" : "The Eclipse of Light",
    "judgment" : "The Eclipse of Light.\n It is encouraging to be persistent in times of need.",
    "line-1" : "Initially a nine means:\n Eclipsing the light in flight.\n He lowers his wings.\n The noble on his wanderings eats nothing for three days.\n But he has where he goes.\n The landlord has to talk about him.",
    "line-2" : "Six in second place means:\n The darkening of the light injures him on the left thigh.\n He is helping with the power of a horse. Salvation.",
    "line-3" : "Nine in third place means:\n The eclipse of the light on the hunt in the south.\n You get her big head.\n One should not expect hurry persistence.",
    "line-4" : "Six in fourth place means:\n It penetrates into the left abdominal cavity.\n One receives the heart of the eclipse of the light\n and leaves gate and yard.",
    "line-5" : "Six in fifth place means:\n Eclipse of light as with Prince Gi.\n Promoting is perseverance.",
    "line-6" : "Above a six means:\n Not light, but dark.\n First he ascended to heaven,\n then he plummeted down into the depths of the earth.",
  },
  {
    "number" : "37",
    "name-interpretation" : "The clan",
    "judgment" : "The clan. Promoting is the perseverance of the woman.",
    "line-1" : "Initially a nine means:\n Firm conclusion within the clan. Regret disappears.",
    "line-2" : "Six in second place means:\n She should not follow her mood.\n It should provide food inside.\n Perseverance brings salvation.",
    "line-3" : "Nine in third place means:\n If there is heatedness in the clan,\n remorse will be overstretched.\n But salvation!\n If woman and child are laughing and laughing,\n it will eventually lead to embarrassment.",
    "line-4" : "Six in fourth place means:\n It is the wealth of the house.\n Great salvation!",
    "line-5" : "Nine in fifth place means:\n A king is approaching his clan, do not be afraid.\n Salvation!",
    "line-6" : "Nine at the top means:\n His work is awesome.\n Finally comes salvation.",
  },
  {
    "number" : "38",
    "name-interpretation" : "The Contrast",
    "judgment" : "The Contrast. In small things salvation.",
    "line-1" : "Initially a nine means:\n Repentance disappears.\n If you lose your horse, do not run after him.\n It comes back by itself.\n If you see evil people, beware of mistakes.",
    "line-2" : "Nine in second place means:\n One meets his master in a narrow alley.\n No blemish.",
    "line-3" : "Six in third place means:\n One sees the car pulled backwards,\n the cattle held fast,\n the human hair and nose cut off.\n Not a good start, but a good ending.",
    "line-4" : "Nine in the fourth place means:\n By contrast,\n one finds a like-minded person\n with whom one can be loyal.\n Despite the danger no blemish.",
    "line-5" : "Six in fifth place means:\n Regret disappears.\n The fellow bites through the shell.\n If you go to him, how would that be a mistake?",
    "line-6" : "Nine at the top means:\n By contrast, you seecompanion\n yourlike a dirt-laden pig,\n like a wagon full of devils.\n First you stretch the bow to him,\n then you put the bow away.\n Not a robber he is, wants to get free to the deadline.\n When going in rain falls, then comes salvation.",
  },
  {
    "number" : "39",
    "name-interpretation" : "The barrier",
    "judgment" : "The barrier. Promoting is the southwest.\n Non-promotional is the northeast.\n It is encouraging to see the big man.\n Perseverance is of salvation.",
    "line-1" : "Initially a six means:\n Walking leads into obstacles, coming finds praise.",
    "line-2" : "Six in second place means:\n The king's servant is in obstructive over the obstruction.\n But it is not his own fault.",
    "line-3" : "Nine in third place means:\n Walking leads into obstacles; Here he comes back.",
    "line-4" : "Six in fourth place means:\n Walking leads to obstacles,\n coming leads to union.",
    "line-5" : "Nine in fifth place means:\n In the midst of the biggest obstacles come friends.",
    "line-6" : "Above a six means:\n Walking leads to obstacles, coming leads to great salvation.\n It is encouraging to see the big man.",
  },
  {
    "number" : "40",
    "name-interpretation" : "The Liberation",
    "judgment" : "The Liberation. Promoting is the southwest.\n When there is nothing left to go to, it\n is the return of salvation.\n If there is anything else to go to,\n then speed is of salvation.",
    "line-1" : "Initially a six means:\n No blemish.",
    "line-2" : "Nine in second place means:\n Three foxes are killed in the field\n and you get a yellow arrow.\n Perseverance is of salvation.",
    "line-3" : "Six in third place means:\n That if one carries a load on his back\n and still drives on the wagon, he\n causes the robbers to come.\n Persistence leads to shame.",
    "line-4" : "Nine in fourth place means:\n Get free from your big toe.\n Then the companion comes,\n and you can trust that.",
    "line-5" : "Six in fifth place means:\n If the noble can only free himself, that brings salvation.\n He shows the commoner that he is serious.",
    "line-6" : "Above a six means:\n The prince shoots for a hawk on a high wall.\n He kills him. Everything is promotional.",
  },
  {
    "number" : "41",
    "name-interpretation" : "The mitigation of",
    "judgment" : "Diminution combined with truthfulness\n exalted salvation without blemish.\n You can be persistent in that.\n It is encouraging to do something.\n How do you do that?\n Two small bowls may be used as victims.",
    "line-1" : "In the beginning a nine means:\n When the shops are ready, going quickly\n is no blemish. But one must consider\n how far one may reduce others.",
    "line-2" : "Nine in second place means:\n Promoting is perseverance.\n To do something is of mischief.\n Without reducing oneself, one\n can increase the others.",
    "line-3" : "Six in the third place means:\n That when three people walk together,another\n they diminish around one.\n When a person wanders, he finds his companion.",
    "line-4" : "Six in the fourth place means:\n If you reduce your shortcomings, you make\n the other one come in a hurry and have joy.\n No blemish.",
    "line-5" : "Six in fifth place means:\n Someone probably does increase it.\n Ten pairs of turtles can not resist that.\n Sublime salvation!",
    "line-6" : "Above a nine means:\n If you are honored without diminishing the other,\n that is not a blemish. Perseverance brings salvation.\n It is encouraging to do something.\n You get a servant, but you do not have a special home anymore.",
  },
  {
    "number" : "42",
    "name-interpretation" : "The increase",
    "judgment" : "The increase. It is encouraging to do something.\n It is encouraging to cross the big water.",
    "line-1" : "At first a nine means:\n It is encouraging to perform great deeds.\n Sublime salvation! No blemish.",
    "line-2" : "Six in second place means:\n Someone probably does increase it.\n Ten pairs of turtles can not resist that.\n Constant persistence brings salvation.\n The king represents him before God. Salvation!",
    "line-3" : "Six in third place means:\n One is honored by ominous events.\n No blemish, if you are true\n and walk in the middle\n and report to the prince with a seal.",
    "line-4" : "Six in the fourth place means:\n If you walk in the middle\n and report to the prince,\n he will follow.\n It is encouraging to be used\n in the relocation of the capital.",
    "line-5" : "Nine in fifth place means:\n If you truly have a kind heart,\n do not ask. Sublime salvation!\n Truly, goodness will be recognized as your virtue.",
    "line-6" : "Nine at the top means:\n He is not enough to increase.\n Someone beats him.\n He does not keep his heart permanently. Mischief!",
  },
  {
    "number" : "43",
    "name-interpretation" : "The breakthrough, (the determination)",
    "judgment" : "The breakthrough.\n Resolutely one must announce the thing at the yard of the king.\n In truth, it must be proclaimed. Danger!\n You have to notify your own city.\n It is not encouraging to take up arms.\n It is encouraging to do something.",
    "line-1" : "At first a nine means:\n Powerful in the forward-moving toes.\n If one goes and is not up to the task,\n one makes a mistake.",
    "line-2" : "Nine in second place means:\n Alarm call. Weapons in the evening and at night.\n Fear nothing.",
    "line-3" : "Nine in third place means:\n Being powerful in the cheekbones brings disaster.\n The noble is determined.\n He walks lonely and comes in the rain.\n He is spattered and grumbled against him.\n No blemish.",
    "line-4" : "Nine in fourth place means:\n There is no skin on the thighs,\n and walking is difficult.\n If one were led like a sheep,\n repentance would disappear.\n But if one hears these words,\n one will not believe them.",
    "line-5" : "Nine in fifth place means:\n That the weed needs firm determination.\n Walking in the middle is free of stains.",
    "line-6" : "Above a six means:\n No call! Finally comes disaster.",
  },
  {
    "number" : "44",
    "name-interpretation" : "The Compromise",
    "judgment" : "The Compromise. The girl is powerful.\n One should not marry such a girl.",
    "line-1" : "Initially a six means:\n You have to stop it with your bike shoe.\n Perseverance is of salvation.\n If you let it go, you experience disaster.\n Even a lean pig has the facility to romp around.",
    "line-2" : "Nine in second place means:\n In the tank is a fish. No blemish!\n Not promotional for guests.",
    "line-3" : "Nine in third place means:\n There is no skin on the thighs\n and walking is difficult.\n If you are mindful of the danger,\n you do not make a big mistake.",
    "line-4" : "Nine in fourth place means:\n There is no fish in the tank.\n From this rises mischief.",
    "line-5" : "Nine in fifth place means:\n Melon covered with willow leaves:\n hidden lines.\n It's falling down from the sky.",
    "line-6" : "Above a nine means:\n He comes with his horns.\n Mortification. No blemish.",
  },
  {
    "number" : "45",
    "name-interpretation" : "The Collection",
    "judgment" : "The Collection. Success.\n The king approaches his temple.\n It is encouraging to see the big man.\n That brings success. Promoting is perseverance.\n Making great sacrifices creates salvation.\n It is encouraging to do something.",
    "line-1" : "Initially a six means:\n If you are true, but not to the end,\n there will soon be confusion, soon collection.\n If you call, you can laugh again after a grip.\n Do not regret. Going is without blemish.",
    "line-2" : "Six in second place means:\n Being carried away brings salvation and remains without blemish.\n If you are true,\n it is also beneficial to make a small sacrifice.",
    "line-3" : "Six in third place means:\n Collection under sighing. Nothing that would be supportive.\n Going is without blemish. Little embarrassment.",
    "line-4" : "Nine in the fourth place means:\n Great salvation! No blemish.",
    "line-5" : "Nine in fifth place means:\n If one has the necessary position in collecting,\n then there is no blemish.\n If some are not really there,\n then it requires sublime, persevering persistence,\n then regret disappears.",
    "line-6" : "Above a six means:\n Lamenting and sighing, tears in streams! No blemish.",
  },
  {
    "number" : "46",
    "name-interpretation" : "The Empordringen",
    "judgment" : "The Empordringen has sublime success.\n You have to see the big man.\n Do not be afraid!\n Departure to the south brings salvation.",
    "line-1" : "Initially a six means:\n Empordringen, which finds trust brings great salvation.",
    "line-2" : "Nine in second place means:\n If one is true,\n it is beneficial to make a small sacrifice.\n No blemish.",
    "line-3" : "Nine in third place means:\n You are going up into an empty city.",
    "line-4" : "Six in the fourth place means:\n The King brings him to Mount Ki. Hail. No blemish.",
    "line-5" : "Six in fifth place means:\n Perseverance brings salvation. You get up on steps.",
    "line-6" : "Above a six means:\n Empordringen in the dark.\n It is encouraging to be perseveringly persistent.",
  },
  {
    "number" : "47",
    "name-interpretation" : "The affliction, (the exhaustion)",
    "judgment" : "The affliction. Success. Persistence.\n The big man works salvation. No blemish.\n If you have something to say, it will not be believed.",
    "line-1" : "Initially a six means:\n One sits under pressure under a bare tree\n and gets into a dark valley.\n You do not see anything for three years.",
    "line-2" : "Nine in second place means:\n You are under pressure for wine and food.\n The man with the scarlet knee joints is just coming.\n It is encouraging to offer sacrifices.\n Breaking up is evil.\n No blemish.",
    "line-3" : "Six in the third place means:\n One is pressed by stone\n and relies on thorns and thistles.\n You go to his house and do not see his wife. Mischief!",
    "line-4" : "Nine in fourth place means:\n He comes very gently, harassed in a golden car.\n Shame, but you come to an end.",
    "line-5" : "Nine in fifth place means:\n Nose and feet are cut off.\n One is beset by that in purple knee joints.\n Gently comes the joy.\n Encouraging is to make sacrifices and donations.",
    "line-6" : "Above a six means:\n He is beset by tendrils.\n He moves uncertainly and says:\n &quot;Movement creates remorse.&quot;\n If one feels remorse and opens up,\n one has salvation.",
  },
  {
    "number" : "48",
    "name-interpretation" : "The fountain",
    "judgment" : "The fountain. You may change the city,\n but you can not change the fountain.\n He does not lose weight and does not increase.\n They come and go and draw from the well.\n If one has almost reached the well water,\n but is not yet down with the rope\n or breaks his pitcher, brings the mischief.",
    "line-1" : "Initially a six means:\n The mud of the well is not drunk:\n no animals come to an old well.",
    "line-2" : "Nine in second place means:\n At the well hole you shoot fish.\n The pitcher is broken and runs.",
    "line-3" : "Nine in third place means:\n The well is clean, but you do not drink from it.\n That is my heart's suffering;\n because you could draw from it.\n If the king were clear, then one would enjoy happiness together.",
    "line-4" : "Six in the fourth place means:\n The well is bricked up, no blemish.",
    "line-5" : "Nine in fifth place means:\n In the well is a clear, cool spring that you can drink.",
    "line-6" : "Above a six means:\n You draw from the well without hindrance.\n He is reliable. Sublime salvation!",
  },
  {
    "number" : "49",
    "name-interpretation" : "The upheaval, (moulting)",
    "judgment" : "The upheaval.\n On your own day, there you will find faith.\n Sublime success, promoted by perseverance.\n Repentance disappears.",
    "line-1" : "At first a nine means:\n One is wrapped in the fur of a yellow cow.",
    "line-2" : "Six in second place means:\n On your own day, you may want to turn around.\n Departure brings salvation. No blemish.",
    "line-3" : "Nine in third place means:\n Departure brings disaster. Perseverance brings danger.\n When the talk of the upheaval has been made three times,\n then one may turn to her and find faith.",
    "line-4" : "Nine in the fourth place means:\n Repentance disappears. One finds faith.\n Changing the state order brings salvation.",
    "line-5" : "Nine in fifth place means:\n The big man changes like a tiger.\n Even before he asks the oracle, he finds faith.",
    "line-6" : "Above a six means:\n The noble changes like a panther.\n The slight grows in the face.\n Departure brings disaster.\n In perseverance brings salvation.",
  },
  {
    "number" : "50",
    "name-interpretation" : "The crucible",
    "judgment" : "The crucible. Sublime salvation. Success.",
    "line-1" : "Initially a six means:\n A pot with his legs tipped over.\n Conveying to remove the tail.\n One takes a concubine for the sake of her son.\n No blemish.",
    "line-2" : "Nine in second place means:\n In the jar is food.\n My comrades are envious,\n but they can not harm me.\n Salvation!",
    "line-3" : "Nine in third place means:\n The handle of the crucible is changed.\n One is handicapped in his change.\n The fat of the pheasant is not eaten.\n When the rain falls, then the repentance is exhausted: at\n last salvation comes.",
    "line-4" : "Nine in fourth place means:\n The crucible breaks your legs.\n The meal of the prince is spilled,\n and the figure is stained.\n Mischief!",
    "line-5" : "Six in fifth place means:\n The crucible has yellow handles, golden bearing rings.\n Promoting is perseverance.",
    "line-6" : "Nine at the top means:\n The crucible has nephrite rings. Great salvation!\n Nothing that would not be supportive.",
  },
  {
    "number" : "51",
    "name-interpretation" : "The excitement, (the shaking, the thunder)",
    "judgment" : "The shaking brings success.\n The shaking comes: Hu, Hu!\n Laughing words: Ha, Ha!\n The shaking terrifies a hundred miles,\n and he does not drop sacrificial spoon and goblet.",
    "line-1" : "At first a nine means:\n The shaking comes: Hu, Hu!\n Followed by laughing words: Ha, Ha!\n Salvation!",
    "line-2" : "Six in second place means:\n Shaking comes with danger.\n One hundred thousand times you lose your treasures\n and must climb the nine hills.\n Do not chase them.\n After seven days you will get it again.",
    "line-3" : "Six in third place means:\n The shaking comes and makes stunned.\n If one acts as a result of the shaking,\n one remains free from misfortune.",
    "line-4" : "Nine in fourth place means:\n The shaking gets into mud.",
    "line-5" : "Six in fifth place means:\n The shaking goes back and forth: danger.\n But you do not lose anything,\n only there are shops.",
    "line-6" : "Above a six means:\n The shock brings decay and fearful look around.\n Leading brings disaster.\n If she has not yet reached her own body,\n but has reached her neighbor,\n it is no blemish.\n The comrades have to talk.",
  },
  {
    "number" : "52",
    "name-interpretation" : "The Keeping Still, the mountain",
    "judgment" : "Stillness of his back,\n so that he no longer feels his body.\n He goes to his yard and does not see his people.\n No blemish.",
    "line-1" : "Initially a six means:\n Keeping his toes still.\n No blemish. Promoting is persevering persistence.",
    "line-2" : "Six in second place means:\n Silence of his calves.\n He can not save the one he follows.\n His heart is not happy.",
    "line-3" : "Nine in third place means:\n Keeping his hips still.\n Stiffening of his sacrum.\n Dangerous. The heart suffocates.",
    "line-4" : "Six in fourth place means:\n Silence of his trunk.\n No blemish.",
    "line-5" : "Six in fifth place means:\n Silence of his jaw.\n The words are okay.\n Repentance disappears.",
    "line-6" : "Nine at the top means:\n Generous silence. Salvation!",
  },
  {
    "number" : "53",
    "name-interpretation" : "Development, (gradual progress)",
    "judgment" : "Development. The girl is married. Salvation!\n Promoting is perseverance.",
    "line-1" : "Initially a six means:\n The wild goose is gradually closing to the shore.\n The young son is in danger.\n There is talk. No blemish.",
    "line-2" : "Six in second place means:\n The wild goose gradually moves towards the rock.\n Eating and drinking in peace and harmony. Salvation!",
    "line-3" : "Nine in third place means:\n Gaining access to The wild goose is gradually the plateau.\n The man moves out and does not return.\n The woman carries a child, but does not give birth to it.\n Mischief!\n It is encouraging to repel robbers.",
    "line-4" : "Six in fourth place means:\n Gaining access to The wild goose is gradually the tree.\n Maybe she gets a flat branch. No blemish.",
    "line-5" : "Nine in fifth place means:\n The wild goose is gradually approaching the summit.\n The woman does not have a child for three years.\n At last she can not prevent anything. Salvation!",
    "line-6" : "Nine at the top means:\n The wild goose is gradually gaining altitude.\n Their feathers can be used for sacred dance.\n Salvation!",
  },
  {
    "number" : "54",
    "name-interpretation" : "The Marriage Girl",
    "judgment" : "The Marriage Girl.\n Businesses bring disaster.\n Nothing that would be supportive.",
    "line-1" : "At first a nine means:\n The marrying girl as a concubine.\n A lame man who can occur.\n Businesses bring salvation.",
    "line-2" : "Nine in second place means:\n One-eyed one who can see.\n Promoting is the persistence of a lonely person.",
    "line-3" : "Six in third place means:\n The marrying girl as a slave.\n She marries as a concubine.",
    "line-4" : "Nine in fourth place means:\n The marrying girl delays the deadline.\n A late marriage comes in their time.",
    "line-5" : "Six in fifth place means:\n The ruler I marries his daughter.\n The princess's embroidered dresses were not as\n splendid as the maid's clothes.\n The moon, which is almost full, brings salvation.",
    "line-6" : "Above a six means:\n The woman holds the basket, but there are no fruits in it.\n The man stabs the sheep, but no blood flows.\n Nothing that would be supportive.",
  },
  {
    "number" : "55",
    "name-interpretation" : "The abundance",
    "judgment" : "The abundance succeeds.\n The king reaches her.\n Do not be sad; you must be like the sun at noon.",
    "line-1" : "At first a nine means:\n When you meet your particular Lord,\n you may be together for ten days,\n and it is not a mistake.\n Going there is recognition.",
    "line-2" : "Six in second place means:\n The curtain is so full\n that you can see the cushions at noon.\n By entering one reaches mistrust and hatred.\n When one awakens him through truth, salvation comes.",
    "line-3" : "Nine in third place means:\n The undergrowth is so abundant\n that one sees the little stars at noon.\n He breaks his right arm. No blemish.",
    "line-4" : "Nine in the fourth place means:\n The curtain is so full\n that you can see the cushions at noon.\n He meets his same master. Salvation!",
    "line-5" : "Six in fifth place means:\n Lines come, blessings and glory come to the fore. Salvation!",
    "line-6" : "Above a six means:\n His house is in abundance.\n He hides his clan.\n He peeks through the gate and no one notices.\n For three years he sees nothing. Mischief!",
  },
  {
    "number" : "56",
    "name-interpretation" : "The Wanderer",
    "judgment" : "The Wanderer. Through smallness succeed.\n The wanderer is perseverance of salvation.",
    "line-1" : "Initially a six means:\n If the wanderer gives himself away with petty things,\n he draws misfortune by doing so.",
    "line-2" : "Six in second place means:\n The hiker comes to the hostel.\n He has his possessions with him.\n He gains persistence from a young servant.",
    "line-3" : "Nine in third place means:\n The hiker burns his hostel.\n He loses the persistence of his young servant.\n Danger.",
    "line-4" : "Nine in fourth place means:\n The hiker rests at an accommodation place.\n He gains his possessions and an ax.\n My heart is not happy.",
    "line-5" : "Six in fifth place means:\n He shoots a pheasant, he falls on the first arrow.\n After all, it brings praise and office.",
    "line-6" : "Above a nine means:\n The bird burns its nest.\n The hiker laughs first,\n then he has to complain and cry.\n He loses the cow in the carelessness. Mischief!",
  },
  {
    "number" : "57",
    "name-interpretation" : "The gentle, the penetrating, the wind",
    "judgment" : "The gentle. By small success.\n It is encouraging to have where you go.\n It is encouraging to see the big man.",
    "line-1" : "Initially a six means:\n In the process and return\n is promoting the perseverance of a warrior.",
    "line-2" : "Nine in second place means:\n Getting under the bed.\n One uses priests and magicians in large numbers.\n Salvation! No blemish.",
    "line-3" : "Nine in third place means:\n Repeated penetration. Mortification.",
    "line-4" : "Six in fourth place means:\n Regret disappears.\n On the hunt you catch three kinds of game.",
    "line-5" : "Nine in fifth place means:\n Perseverance brings salvation. Regret disappears.\n Nothing that is not promotional.\n No beginning, but an end.\n Three days before the change, three days\n after the change. Salvation!",
    "line-6" : "Nine at the top means:\n Getting under the bed.\n He loses his possessions and his ax.\n Perseverance brings disaster.",
  },
  {
    "number" : "58",
    "name-interpretation" : "The cheerful, the lake",
    "judgment" : "The cheerful. Success. Cheap is perseverance.",
    "line-1" : "At first a nine means:\n Happy cheerfulness. Salvation!",
    "line-2" : "Nine in second place means:\n True serenity. Salvation! Repentance disappears.",
    "line-3" : "Six in third place means:\n Coming joy. Mischief!",
    "line-4" : "Nine in fourth place means:\n Considered cheerfulness is not reassured.\n After Abtun the mistake you have joy.",
    "line-5" : "Nine in fifth place means:\n Truth against the destructor is dangerous.",
    "line-6" : "Above a six means:\n Seductive cheerfulness.",
  },
  {
    "number" : "59",
    "name-interpretation" : "The Resolution",
    "judgment" : "The Resolution. Success.\n The king approaches his temple.\n It is encouraging to cross the big water.\n Promoting is perseverance.",
    "line-1" : "Initially a six means:\n He brings help with the power of a horse. Salvation!",
    "line-2" : "Nine in second place means:\n In the resolution, he runs towards his support.\n Repentance disappears.",
    "line-3" : "Six in third place means:\n He dissolves his ego. No mercy.",
    "line-4" : "Six in fourth place means:\n He breaks away from his flock. Sublime salvation!\n By dissolution follows accumulation.\n That's something ordinary people do not think about.",
    "line-5" : "Nine in fifth place means:\n Dissolving as sweat are his loud calls.\n Resolution! A king dwells without blemish.",
    "line-6" : "Above a nine means:\n He dissolves his blood.\n Leaving, staying away, going out is without blemish.",
  },
  {
    "number" : "60",
    "name-interpretation" : "The restriction",
    "judgment" : "Restriction. Success.\n Bitter restriction should not be practiced persistently.",
    "line-1" : "Initially a nine means:\n Do not go to the door and yard is not a flaw.",
    "line-2" : "Nine in second place means:\n Not to go out to the gate and court brings disaster.",
    "line-3" : "Six in third place means:\n That anyone who knows no limitation will have to complain.\n No blemish.",
    "line-4" : "Six in fourth place means:\n Satisfied restriction. Success.",
    "line-5" : "Nine in fifth place means:\n Sweet limitation brings salvation.\n Going there brings respect.",
    "line-6" : "Above a six means:\n Bitter restriction: Perseverance brings disaster.\n Regret disappears.",
  },
  {
    "number" : "61",
    "name-interpretation" : "Inner truth",
    "judgment" : "Inner truth. Pigs and fish. Salvation!\n It is encouraging to cross the big water.\n Promoting is perseverance.",
    "line-1" : "Initially a nine means:\n Being ready brings salvation.\n If ulterior motives are there, that is disconcerting.",
    "line-2" : "Nine in second place means:\n A calling crane in the shade.\n His cub answers him.\n I have a good mug. I want to share it with you.",
    "line-3" : "Six in third place means:\n He finds a comrade,\n soon he drums, soon he stops.\n Soon he is sobbing, soon he is singing.",
    "line-4" : "Six in fourth place means:\n The moon is almost full.\n The team horse is lost.\n No blemish.",
    "line-5" : "Nine in fifth place means:\n He has truth that chained.\n No blemish.",
    "line-6" : "Above a nine means:\n Hahnenruf, which penetrates to the sky.\n Perseverance brings disaster.",
  },
  {
    "number" : "62",
    "name-interpretation" : "Little Overweight",
    "judgment" : "Of Little Overweight. Success.\n Promoting is perseverance.\n You may do little things, you should not do great things.\n The flying bird brings the message:\n It's not good to go up,\n it's good to stay down. Great salvation!",
    "line-1" : "Initially a six means:\n The bird comes through flying into evil.",
    "line-2" : "Six in second place means:\n She passes her ancestor and meets the ancestress.\n He does not reach his prince and meets the official.\n No blemish.",
    "line-3" : "Nine in third place means:\n If you do not look forward to anything,\n someone comes from behind and hits you.\n Mischief!",
    "line-4" : "Nine in fourth place means:\n No blemish. Without passing, he meets him.\n Going there brings danger. You have to be careful.\n Do not handle. Be persevering.",
    "line-5" : "Six in fifth place means:\n Dense clouds, no rain from our western area.\n The prince shoots and hits those in the cave.",
    "line-6" : "Above a six means:\n Without meeting him, he passes him.\n The flying bird leaves him. Mischief!\n That means bad luck and harm.",
  },
  {
    "number" : "63",
    "name-interpretation" : "After completion",
    "judgment" : "Succeed in the small. Promoting is perseverance.\n In the beginning salvation, in the end turmoil.",
    "line-1" : "At first a nine means:\n He inhibits his wheels.\n He comes with his tail in the water.\n No blemish.",
    "line-2" : "Six in second place means:\n The woman loses her car curtain.\n Do not run after him. On the seventh day you get him.",
    "line-3" : "Nine in third place means:\n The high ancestor chastises the devil country.\n After three years he overcomes it.\n You are not allowed to use common.",
    "line-4" : "Six in fourth place means:\n The most beautiful clothes give rags.\n Be careful all day.",
    "line-5" : "Nine in fifth place means:\n The neighbor in the east slaughtering an ox\n does not get as much real happiness\n as the neighbor in the west with his little victim.",
    "line-6" : "Above a six means:\n He comes with his head into the water. Danger.",
  },
  {
    "number" : "64",
    "name-interpretation" : "Before Completion",
    "judgment" : "Before Completion. Success.\n But if the little fox,\n when he has almost completed the transition,\n comes with his tail into the water,\n then there is nothing that would be beneficial.",
    "line-1" : "Initially a six means:\n He comes with his tail into the water.\n Shameful.",
    "line-2" : "Nine in second place means:\n He inhibits his wheels.\n Perseverance brings salvation.",
    "line-3" : "Six in third place means:\n Attack brings disaster before completion.\n It is encouraging to cross the big water.",
    "line-4" : "Nine in the fourth place means:\n Perseverance brings salvation. Regret disappears.\n Shake to chastise the devil country.\n For three years there is reward with big rich people.",
    "line-5" : "Six in fifth place means:\n Perseverance brings salvation. No mercy.\n The light of the noble is true.\n Salvation!",
    "line-6" : "Nine at the top means:\n In true trust, one drinks wine.\n No blemish. But if you wet your head,\n you lose it in truth.",
  },
]
}
}
