export class ChangesText {
static get name() { return "wilhelm" }
static get edition() { return "text-wilhelm.xml" }
static get version() { return "2018-06-04-17-39-58" }
static get changes() { return [
  {
    "number" : "1",
    "name-interpretation" : "Das Schöpferische",
    "judgment" : "Das Schöpferische wirkt erhabenes Gelingen,\n fördernd durch Beharrlichkeit.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Verdeckter Drache, handle nicht!",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Erscheinender Drache auf dem Feld.\n Fördernd ist es, den großen Mann zu sehen.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Der Edle ist den ganzen Tag schöpferisch tätig.\n Des Abends noch ist er voll innerer Sorge.\n Gefahr. Kein Makel.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Schwankender Aufschwung über die Tiefe.\n Kein Makel.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Fliegender Drache am Himmel.\n Fördernd ist es, den großen Mann zu sehen.",
    "line-6" : "Oben eine Neun bedeutet:\n Hochmütiger Drache wird zu bereuen haben.",
    "line-7" : "Wenn lauter Neunen erscheinen, bedeutet das:\n Es erscheint eine Schar von Drachen ohne Haupt. Heil! Es erscheint eine Schar von Drachen ohne Haupt. Heil!",
  },
  {
    "number" : "2",
    "name-interpretation" : "Das Empfangende",
    "judgment" : "Das Empfangende wirkt erhabenes Gelingen,\n fördernd durch die Beharrlichkeit einer Stute.\n Hat der Edle etwas zu unternehmen und will voraus,\n so geht er irre; doch folgt er nach, so findet er Leitung.\n Fördernd ist es, im Westen und Süden Freunde zu finden,\n im Osten und Norden der Freunde zu entraten.\n Ruhige Beharrlichkeit bringt Heil.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Tritt man auf Reif, so naht das feste Eis.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Gerade, rechtwinklig, groß.\n Ohne Absicht bleibt doch nichts ungefördert.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Verborgene Linien; man vermag beharrlich zu bleiben.\n Folgst du etwa eines Königs Diensten,\n so suche nicht Werke, aber vollende!",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Zugebundener Sack. Kein Makel; kein Lob.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Gelbes Untergewand bringt erhabenes Heil.",
    "line-6" : "Oben eine Sechs bedeutet:\n Drachen kämpfen auf dem Anger.\n Ihr Blut ist schwarz und gelb.",
    "line-7" : "Wenn lauter Sechsen erscheinen, bedeutet das:\n Fördernd ist dauernde Beharrlichkeit. Fördernd ist dauernde Beharrlichkeit.",
  },
  {
    "number" : "3",
    "name-interpretation" : "Die Anfangsschwierigkeit",
    "judgment" : "Die Anfangsschwierigkeit wirkt erhabenes Gelingen.\n Fördernd durch Beharrlichkeit.\n Man soll nichts unternehmen.\n Fördernd ist es, Gehilfen einzusetzen.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Zögern und Hemmung.\n Fördernd ist es, beharrlich zu bleiben.\n Fördernd ist es, Gehilfen einzusetzen.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Schwierigkeiten türmen sich.\n Pferd und Wagen trennen sich.\n Nicht Räuber er ist,\n will freien zur Frist.\n Das Mädchen ist keusch, verspricht sich nicht.\n Zehn Jahre, dann verspricht sie sich.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Wer den Hirsch jagt ohne Förster,\n der verirrt sich nur im Wald.\n Der Edle versteht die Zeichen der Zeit\n und steht lieber ab.\n Weitermachen bringt Beschämung.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Pferd und Wagen trennen sich.\n Suche nach Vereinigung.\n Hingehen bringt Heil.\n Alles wirkt fördernd.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Schwierigkeiten im Segnen.\n Kleine Beharrlichkeit bringt Heil,\n große Beharrlichkeit bringt Unheil.",
    "line-6" : "Oben eine Sechs bedeutet:\n Pferd und Wagen trennen sich.\n Blutige Tränen ergießen sich.",
  },
  {
    "number" : "4",
    "name-interpretation" : "Die Jugendtorheit",
    "judgment" : "Jugendtorheit hat Gelingen.\n Nicht ich suche den jungen Toren,\n der junge Tor sucht mich.\n Beim ersten Orakel gebe ich Auskunft.\n Fragt er zwei-, dreimal, so ist das Belästigung.\n Wenn er belästigt, so gebe ich keine Auskunft.\n Fördernd ist Beharrlichkeit.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Um den Toren zu entwickeln,\n ist es fördernd, den Menschen in Zucht zu nehmen.\n Man soll die Fesseln abnehmen.\n So weitermachen bringt Beschämung.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Die Toren ertragen in Milde, bringt Heil.\n Die Frauen zu nehmen wissen, bringt Heil.\n Der Sohn ist dem Hauswesen gewachsen.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Nicht sollst Du ein Mädchen nehmen,\n das einen ehernen Mann sieht\n und sich nicht im Besitz behält.\n Nichts ist fördernd.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Beschränkte Jugendtorheit bringt Beschämung.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Kindliche Torheit bringt Heil.",
    "line-6" : "Oben eine Neun bedeutet:\n Beim Bestrafen der Torheit ist es nicht fördernd,\n Übergriffe zu begehen.\n Fördernd ist nur, Übergriffe abzuwehren.",
  },
  {
    "number" : "5",
    "name-interpretation" : "Das Warten, (die Ernährung)",
    "judgment" : "Das Warten.\n Wenn du wahrhaftig bist, so hast du Licht und Gelingen.\n Beharrlichkeit bringt Heil.\n Fördernd ist es, das große Wasser zu durchqueren.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Warten auf dem Anger.\n Fördernd ist es, im Dauernden zu bleiben.\n Kein Makel.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Warten auf dem Sand.\n Es gibt ein wenig Gerede.\n Das Ende bringt Heil.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Warten im Schlamm\n bewirkt das Kommen des Feindes.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Warten im Blut.\n Heraus aus dem Loch.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Warten bei Wein und Speise.\n Beharrlichkeit bringt Heil.",
    "line-6" : "Oben eine Sechs bedeutet:\n Man gerät in das Loch.\n Da kommen ungebetener Gäste drei.\n Ehre sie, so kommt am Ende Heil.",
  },
  {
    "number" : "6",
    "name-interpretation" : "Der Streit",
    "judgment" : "Der Streit: Du bist wahrhaftig und wirst gehemmt.\n Sorgliches Innehalten auf halbem Weg bringt Heil.\n Zu Ende führen bringt Unheil.\n Fördernd ist es, den großen Mann zu sehen.\n Nicht fördernd ist es, das große Wasser zu durchqueren.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Wenn man die Sache nicht verewigt,\n so gibt es ein kleines Gerede.\n Am Ende kommt Heil.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Man kann nicht streiten, kehrt heim und weicht aus.\n Die Menschen seiner Stadt, dreihundert Häuser,\n bleiben frei von Schuld.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Von alter Tugend sich nähren gibt Beharrlichkeit.\n Gefahr, am Ende kommt Heil.\n Folgst du etwa eines Königs Diensten,\n so suche nicht Werke.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Man kann nicht streiten,\n kehrt um und fügt sich dem Geschick,\n ändert sich und findet Frieden in Beharrlichkeit.\n Heil!",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Streiten vor ihm bringt erhabenes Heil.",
    "line-6" : "Oben eine Neun bedeutet:\n Wenn einem etwa auch ein Ledergürtel verliehen wird,\n am Ende eines Morgens wird er ihm dreimal entrissen.",
  },
  {
    "number" : "7",
    "name-interpretation" : "Das Heer",
    "judgment" : "Das Heer braucht Beharrlichkeit\n und einen starken Mann.\n Heil ohne Makel.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Ein Heer muß ausziehen nach der Ordnung.\n Ist die nicht gut, droht Unheil.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Inmitten des Heeres!\n Heil! Kein Makel!\n Der König verleiht dreifache Auszeichnung.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Das Heer führt etwa im Wagen Leichen. Unheil!",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Das Heer zieht sich zurück. Kein Makel.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Im Feld ist ein Wild. Es ist fördernd, es zu fangen.\n Ohne Makel.\n Der Älteste führe das Heer.\n Der Jüngere fährt Leichen,\n da bringt Beharrlichkeit Unheil.",
    "line-6" : "Oben eine Sechs bedeutet:\n Der große Fürst erläßt Befehle,\n gründet Staaten, belehnt Familien.\n Gemeine Menschen soll man nicht benützen.",
  },
  {
    "number" : "8",
    "name-interpretation" : "Das Zusammenhalten",
    "judgment" : "Das Zusammenhalten bringt Heil.\n Ergründe das Orakel nochmals,\n ob du Erhabenheit, Dauer und Beharrlichkeit hast;\n dann ist kein Makel da.\n Die Unsicheren kommen allmählich herbei.\n Wer zu spät kommt, hat Unheil.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Halte wahr und treu zu ihm: das ist kein Makel.\n Wahrheit wie eine volle Tonschüssel:\n so kommt schließlich von außen her das Heil.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Halte zu ihm im Innern. Beharrlichkeit bringt Heil.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Du hältst zusammen mit Menschen,\n die nicht die rechten sind.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Auch äußerlich halte zu ihm. Beharrlichkeit bringt Heil.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Offenbarung des Zusammenhaltens.\n Der König läßt bei der Jagd nur von drei Seiten treiben\n und verzichtet auf das Wild, das vorne abbiegt.\n Die Bürger bedürfen nicht der Warnung. Heil!",
    "line-6" : "Oben eine Sechs bedeutet:\n Er findet zum Zusammenhalten kein Haupt. Unheil.",
  },
  {
    "number" : "9",
    "name-interpretation" : "Des Kleinen Zähmungskraft",
    "judgment" : "Des Kleinen Zähmungskraft hat Gelingen.\n Dichte Wolken, kein Regen von unserm westlichen Gebiet.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Wiederkehr auf den Weg. Wie wäre das ein Makel! Heil!",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Läßt sich mitziehen zur Wiederkehr. Heil!",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Dem Wagen springen die Speichen ab.\n Mann und Frau verdrehen die Augen.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Bist du wahrhaftig, so schwindet Blut und weicht Angst.\n Kein Makel.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Bist du wahrhaftig und treu verbunden,\n so bist du reich in deinem Nächsten.",
    "line-6" : "Oben eine Neun bedeutet:\n Es kommt zum Regen, es kommt zur Ruhe.\n Das ist der dauernden Wirkung des Charakters zu verdanken.\n Die Frau kommt durch Beharrlichkeit in Gefahr.\n Der Mond ist fast voll. Macht der Edle fort,\n so kommt Unheil.",
  },
  {
    "number" : "10",
    "name-interpretation" : "Das Auftreten",
    "judgment" : "Auftreten auf des Tigers Schwanz.\n Er beißt den Menschen nicht. Gelingen.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Einfaches Auftreten. Fortschreiten ohne Makel.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Auftreten auf schlichter, ebener Bahn.\n Eines dunklen Mannes Beharrlichkeit bringt Heil.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Ein Einäugiger kann sehen, ein Lahmer kann auftreten.\n Er tritt auf des Tigers Schwanz. Der beißt den Menschen.\n Unheil!\n Ein Krieger handelt so für seinen großen Fürsten.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Er tritt auf des Tigers Schwanz.\n Vorsicht und Behutsamkeit führt endlich zum Heil.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Entschlossenes Auftreten.\n Beharrlichkeit bei Bewußtsein der Gefahr.",
    "line-6" : "Oben eine Neun bedeutet:\n Blicke auf dein Auftreten und prüfe die günstigen Zeichen.\n Ist alles vollkommen, so kommt erhabenes Heil.",
  },
  {
    "number" : "11",
    "name-interpretation" : "Der Friede",
    "judgment" : "Der Friede. Das Kleine geht hin, das Große kommt her.\n Heil! Gelingen!",
    "line-1" : "Anfangs eine Neun bedeutet:\n Zieht man Bandgras aus, so geht der Rasen mit.\n Jeder nach seiner Art. Unternehmungen bringen Heil.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Die Ungebildeten in Milde tragen,\n entschlossen den Fluß durchschreiten,\n das Ferne nicht vernachlässigen,\n die Genossen nicht berücksichtigen:\n so mag man es fertigbringen, in der Mitte zu wandeln.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Keine Ebene, auf die nicht ein Abhang folgt,\n kein Hingang, auf den nicht die Wiederkehr folgt.\n Ohne Makel ist, wer beharrlich bleibt in Gefahr.\n Beklage dich nicht über diese Wahrheit,\n genieße das Glück, das du noch hast.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Er flattert hernieder, nicht pochend auf Reichtum,\n zusammen mit seinem Nächsten, arglos und wahrhaftig.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Der Herrscher I gibt seine Tochter in die Ehe.\n Das bringt Segen und erhabenes Heil.",
    "line-6" : "Oben eine Sechs bedeutet:\n Der Wall fällt wieder in den Graben.\n Jetzt brauche keine Heere.\n In der eigenen Stadt verkünde deine Befehle.\n Beharrlichkeit bringt Beschämung.",
  },
  {
    "number" : "12",
    "name-interpretation" : "Die Stockung",
    "judgment" : "Die Stockung.\n Schlechte Menschen sind nicht fördernd\n für die Beharrlichkeit des Edlen.\n Das Große geht hin, das Kleine kommt herbei.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Zieht man Bandgras aus, so geht der Rasen mit.\n Jeder nach seiner Art.\n Beharrlichkeit bringt Heil und Gelingen.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Sie tragen und dulden,\n das bedeutet für die Gemeinen Heil.\n Dem großen Mann dient die Stockung zum Gelingen.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Sie tragen Scham.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Wer auf Befehl des Höchsten wirkt, bleibt ohne Makel.\n Die Gleichgesinnten genießen des Segens.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Die Stockung läßt nach. Dem großen Manne Heil!\n „Wenn es mißlänge, wenn es mißlänge“\n Daher bindet er es an ein Bündel von Maulbeerstauden.",
    "line-6" : "Oben eine Neun bedeutet:\n Die Stockung hört auf.\n Erst Stockung, dann Heil!",
  },
  {
    "number" : "13",
    "name-interpretation" : "Gemeinschaft mit Menschen",
    "judgment" : "Gemeinschaft mit Menschen im Freien: Gelingen.\n Fördernd ist es, das große Wasser zu durchqueren.\n Fördernd ist des Edlen Beharrlichkeit.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Gemeinschaft mit Menschen im Tore. Kein Makel.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Gemeinschaft mit Menschen im Klan: Beschämung.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Versteckt Waffen im Dickicht,\n steigt auf den hohen Hügel davor.\n Drei Jahre lang erhebt er sich nicht.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Er steigt auf seine Mauer, er kann nicht angreifen. Heil!",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Die gemeinsamen Menschen weinen erst und klagen,\n aber nachher lachen sie.\n Nach großen Kämpfen gelingt es ihnen, sich zu treffen.",
    "line-6" : "Oben eine Neun bedeutet:\n Gemeinschaft mit Menschen auf dem Anger: keine Reue.",
  },
  {
    "number" : "14",
    "name-interpretation" : "Der Besitz von Großem",
    "judgment" : "Der Besitz von Großem: Erhabenes Gelingen!",
    "line-1" : "Anfangs eine Neun bedeutet:\n Keine Beziehung zu Schädlichem, das ist nicht ein Makel.\n Bleibt man der Schwierigkeit bewußt,\n so bleibt man ohne Makel.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Ein großer Wagen zum Beladen.\n Man mag etwas unternehmen. Kein Makel.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Ein Fürst bringt ihn dem Sohn des Himmels dar.\n Ein kleiner Mensch kann das nicht.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Er macht einen Unterschied\n zwischen sich und seinem Nächsten.\n Kein Makel.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Wessen Wahrheit umgänglich ist und\n doch würdig, der hat Heil.",
    "line-6" : "Oben eine Neun bedeutet:\n Vom Himmel her wird er gesegnet, Heil!\n Nichts, das nicht fördernd ist.",
  },
  {
    "number" : "15",
    "name-interpretation" : "Die Bescheidenheit",
    "judgment" : "Bescheidenheit schafft Gelingen.\n Der Edle bringt zu Ende.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Ein bescheiden-bescheidener Edler\n mag das große Wasser durchqueren. Heil!",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Sich äußernde Bescheidenheit. Beharrlichkeit bringt Heil.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Ein verdienstvoll-bescheidener Edler bringt zu Ende.\n Heil!",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Nichts, das nicht fördernd wäre\n für Bescheidenheit in der Bewegung.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Nicht pochen auf Reichtum seinem Nächsten gegenüber.\n Fördernd ist es, mit Gewalt anzugreifen.\n Nichts, das nicht fördernd wäre.",
    "line-6" : "Oben eine Sechs bedeutet:\n Sich äußernde Bescheidenheit.\n Fördernd ist es, Heere marschieren zu lassen,\n um die eigene Stadt und das eigene Land zu züchtigen.",
  },
  {
    "number" : "16",
    "name-interpretation" : "Die Begeisterung",
    "judgment" : "Die Begeisterung. Fördernd ist es,\n Gehilfen einzusetzen und Heere marschieren zu lassen.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Begeisterung, die sich äußert, bringt Unheil.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Fest wie ein Stein. Kein ganzer Tag.\n Beharrlichkeit bringt Heil.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Nach oben blickende Begeisterung schafft Reue.\n Zögern bringt Reue.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Der Ursprung der Begeisterung. Er erreicht Großes.\n Zweifle nicht!\n Die Freunde scharen sich um dich\n wie um eine Haarspange.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Beharrlich krank und stirbt doch immer nicht.",
    "line-6" : "Oben eine Sechs bedeutet:\n Verblendete Begeisterung.\n Aber wenn man nach der Vollendung zur Änderung\n kommt, so ist das kein Makel.",
  },
  {
    "number" : "17",
    "name-interpretation" : "Die Nachfolge",
    "judgment" : "Die Nachfolge hat erhabenes Gelingen.\n Fördernd ist Beharrlichkeit. Kein Makel.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Das Maßgebende ändert sich. Beharrlichkeit bringt Heil.\n Zur Tür hinausgehen im Verkehr schafft Werke.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Hängt man sich an den kleinen Knaben,\n so verliert man den starken Mann.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Hängt man dem starken Mann an,\n so verliert man den kleinen Knaben.\n Durch Nachfolge findet man, was man sucht.\n Fördernd ist es, beharrlich zu bleiben.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Die Nachfolge schafft Erfolg. Beharrlichkeit bringt Unheil.\n Mit Wahrhaftigkeit auf dem Weg zu wandeln,\n bringt Klarheit.\n Wie könnte das ein Makel sein?",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Wahrhaft im Guten. Heil!",
    "line-6" : "Oben eine Sechs bedeutet:\n Er findet feste Anhänglichkeit\n und wird noch dazu gebunden.\n Der König stellt ihn dem Westberg vor.",
  },
  {
    "number" : "18",
    "name-interpretation" : "Die Arbeit am Verdorbenen",
    "judgment" : "Die Arbeit am Verdorbenen hat erhabenes Gelingen.\n Fördernd ist es, das große Wasser zu durchqueren.\n Vor dem Anfangspunkt drei Tage,\n nach dem Anfangspunkt drei Tage.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Zurechtbringen des vom Vater Verdorbenen.\n Wenn ein Sohn da ist,\n bleibt auf dem heimgegangenen Vater kein Makel.\n Gefahr. Schließlich Heil.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Zurechtbringen des von der Mutter Verdorbenen.\n Man darf nicht zu beharrlich sein.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Zurechtbringen des vom Vater Verdorbenen.\n Ein wenig wird es Reue geben. Kein großer Makel.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Dulden des vom Vater Verdorbenen.\n Beim Fortmachen sieht man Beschämung.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Zurechtbringen des vom Vater Verdorbenen.\n Man findet Lob.",
    "line-6" : "Oben eine Neun bedeutet:\n Dient nicht Königen und Fürsten.\n Steckt sich höhere Ziele.",
  },
  {
    "number" : "19",
    "name-interpretation" : "Die Annäherung",
    "judgment" : "Die Annäherung hat erhabenes Gelingen.\n Fördernd ist Beharrlichkeit.\n Kommt der achte Monat, so gibt’s Unheil.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Gemeinsame Annäherung. Beharrlichkeit bringt Heil.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Gemeinsame Annäherung. Heil! Alles ist fördernd.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Behagliche Annäherung. Nichts, das fördernd wäre.\n Erreicht man Trauer darüber, so wird man ohne Makel.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Vollkommene Annäherung. Kein Makel.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Weise Annäherung. Das ist recht für\n einen großen Fürsten. Heil!",
    "line-6" : "Oben eine Sechs bedeutet:\n Großherzige Annäherung. Heil. Kein Makel.",
  },
  {
    "number" : "20",
    "name-interpretation" : "Die Betrachtung, (der Anblick)",
    "judgment" : "Die Betrachtung.\n Die Waschung ist geschehen, aber noch nicht die Darbringung.\n Vertrauensvoll blicken sie zu ihm auf.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Knabenhaftes Betrachten.\n Für einen geringen Menschen kein Makel.\n Für einen Edlen beschämend.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Betrachtung durch die Türspalte.\n Fördernd ist die Beharrlichkeit einer Frau.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Betrachtung meines Lebens entscheidet\n über Fortschritt oder Rückzug.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Betrachtung des Lichtes des Reiches.\n Fördernd ist es, als Gast eines Königs zu wirken.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Betrachtung meines Lebens.\n Der Edle ist ohne Makel.",
    "line-6" : "Oben eine Neun bedeutet:\n Betrachtung seines Lebens.\n Der Edle ist ohne Makel.",
  },
  {
    "number" : "21",
    "name-interpretation" : "Das Durchbeißen",
    "judgment" : "Das Durchbeißen hat Gelingen.\n Fördernd ist es, Gericht walten zu lassen.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Steckt mit den Füßen im Block, daß die Zehen verschwinden.\n Kein Makel.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Beißt durch weiches Fleisch, daß die Nase verschwindet.\n Kein Makel.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Beißt auf altes Dörrfleisch und trifft auf Giftiges.\n Kleine Beschämung. Kein Makel.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Beißt auf getrocknetes Knorpelfleisch.\n Erhält Metallpfeile.\n Fördernd ist es,\n der Schwierigkeiten eingedenk und beharrlich zu sein.\n Heil!",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Beißt auf getrocknetes Muskelfleisch.\n Erhält gelbes Gold.\n Beharrlich der Gefahr bewußt sein. Kein Makel.",
    "line-6" : "Oben eine Neun bedeutet:\n Steckt mit dem Hals im hölzernen Kragen,\n daß die Ohren verschwinden.\n Unheil!",
  },
  {
    "number" : "22",
    "name-interpretation" : "Die Anmut",
    "judgment" : "Anmut hat Gelingen.\n Im Kleinen ist es fördernd, etwas zu unternehmen.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Macht seine Zehen anmutig, verläßt den Wagen und geht.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Macht seinen Kinnbart anmutig.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Anmutig und feucht.\n Dauernde Beharrlichkeit bringt Heil.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Anmut oder Einfachheit?\n Ein weißes Pferd kommt wie geflogen:\n Nicht Räuber er ist, will freien zur Frist.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Anmut in Hügeln und Gärten.\n Das Seidenbündel ist ärmlich und klein.\n Beschämung, doch schließlich Heil.",
    "line-6" : "Oben eine Neun bedeutet:\n Schlichte Anmut.\n Kein Makel.",
  },
  {
    "number" : "23",
    "name-interpretation" : "Die Zersplitterung",
    "judgment" : "Die Zersplitterung. Nicht fördernd ist es, wohin zu gehen.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Das Bett wird zersplittert am Bein.\n Die Beharrlichen werden vernichtet. Unheil.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Das Bett wird zersplittert am Rand.\n Die Beharrlichen werden vernichtet. Unheil.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Er zersplittert sich mit Ihnen. Kein Makel.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Das Bett wird zersplittert bis zur Haut. Unheil.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Ein Zug Fische. Durch die Palastdamen kommt Gunst.\n Alles ist förderlich.",
    "line-6" : "Oben eine Neun bedeutet:\n Eine große Frucht ist noch ungegessen da.\n Der Edle erhält einen Wagen.\n Dem Gemeinen zersplittert sein Haus.",
  },
  {
    "number" : "24",
    "name-interpretation" : "Die Wiederkehr, (die Wendezeit)",
    "judgment" : "Die Wiederkehr. Gelingen.\n Ausgang und Eingang ohne Fehl.\n Freunde kommen ohne Makel.\n Hin und her geht der Weg.\n Am siebten Tage kommt die Wiederkehr.\n Fördernd ist es, zu haben, wohin man geht.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Wiederkehr aus geringer Entfernung.\n Es bedarf keiner Reue.\n Großes Heil!",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Ruhige Wiederkehr. Heil!",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Mehrfache Wiederkehr. Gefahr. Kein Makel.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n In der Mitte der andern wandelnd,\n kehrt man allein wieder.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Großzügige Wiederkehr. Keine Reue.",
    "line-6" : "Oben eine Sechs bedeutet:\n Verfehlung der Wiederkehr. Unheil.\n Unglück von außen und innen.\n Wenn man so Heere marschieren läßt,\n wird man schließlich eine große Niederlage erleiden,\n so daß es für den Landesherrn unheilvoll ist.\n Zehn Jahre lang ist man nicht mehr imstande anzugreifen.",
  },
  {
    "number" : "25",
    "name-interpretation" : "Die Unschuld, (das Unerwartete)",
    "judgment" : "Die Unschuld. Erhabenes Gelingen.\n Fördernd ist Beharrlichkeit.\n Wenn jemand nicht recht ist, so hat er Unglück,\n und nicht fördernd ist es, irgend etwas zu unternehmen.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Unschuldiger Wandel bringt Heil!",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Wenn man beim Pflügen nicht ans Ernten denkt\n und beim Roden nicht an das Benützen des Feldes:\n dann ist es fördernd, etwas zu unternehmen.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Unverschuldetes Unglück:\n Die Kuh, die von jemand angebunden war,\n ist des Wanderers Gewinn, des Bürgers Verlust.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Wer vermag beharrlich zu sein, bleibt ohne Makel.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Bei unverschuldeter Krankheit gebrauche keine Arznei.\n Es wird schon von selber gut werden.",
    "line-6" : "Oben eine Neun bedeutet:\n Unschuldiges Handeln bringt Unglück.\n Nichts ist fördernd.",
  },
  {
    "number" : "26",
    "name-interpretation" : "Des Großen Zähmungskraft",
    "judgment" : "Des Großen Zähmungskraft.\n Fördernd ist Beharrlichkeit.\n Nicht zu Hause essen bringt Heil.\n Fördernd ist es, das große Wasser zu durchqueren.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Es ist Gefahr da. Fördernd ist es, abzustehen.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Dem Wagen werden die Achsenlager abgenommen.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Ein gutes Pferd, das andern folgt.\n Fördernd ist Bewußtsein der Gefahr und Beharrlichkeit.\n Täglich übe dich im Wagenfahren und Waffenschutz.\n Fördernd ist es, zu haben, wohin man geht.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Das Schutzbrett eines jungen Stieres.\n Großes Heil!",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Eines verschnittenen Ebers Zahn. Heil!",
    "line-6" : "Oben eine Neun bedeutet:\n Man erlangt den Himmelsweg. Gelingen.",
  },
  {
    "number" : "27",
    "name-interpretation" : "Die Mundwinkel, (die Ernährung)",
    "judgment" : "Die Mundwinkel. Beharrlichkeit bringt Heil.\n Sieh auf die Ernährung und womit einer selbst sucht\n seinen Mund zu füllen.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Du läßt deine Zauberschildkröte fahren\n und blickst nach mir mit herabhängenden Mundwinkeln.\n Unheil!",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Nach dem Gipfel sich wenden um Ernährung.\n Vom Wege abweichen, um von dem Hügel\n Ernährung zu suchen:\n wenn man so fortmacht, bringt es Unheil.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Abweichen von der Ernährung.\n Beharrlichkeit bringt Unheil.\n Zehn Jahre handle nicht danach. Nichts ist fördernd.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Nach dem Gipfel sich wenden um Ernährung bringt Heil.\n Mit scharfen Augen wie ein Tiger umherspähen\n in unersättlichem Begehren. Kein Makel.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Abweichen vom Weg.\n Bleiben in Beharrlichkeit bringt Heil.\n Man soll nicht das große Wasser durchqueren.",
    "line-6" : "Oben eine Neun bedeutet:\n Die Quelle der Ernährung.\n Bewußtsein der Gefahr bringt Heil.\n Fördernd ist es, das große Wasser zu durchqueren.",
  },
  {
    "number" : "28",
    "name-interpretation" : "Des Großen Übergewicht",
    "judgment" : "Des Großen Übergewicht. Der Firstbalken biegt sich durch.\n Fördernd ist es, zu haben, wohin man gehe. Gelingen.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Unterlegen mit weißem Schilfgras.\n Kein Makel.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Ein trockener Pappelbaum treibt einen Wurzelsproß.\n Ein älterer Mann bekommt eine junge Frau.\n Alles ist fördernd.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Der Firstbalken biegt sich durch. Unheil.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Der Firstbalken wird gestützt. Heil.\n Sind Hintergedanken da, ist es beschämend.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Eine dürre Pappel treibt Blüten.\n Ein älteres Weib bekommt einen Mann.\n Kein Makel. Kein Lob.",
    "line-6" : "Oben eine Sechs bedeutet:\n Man muß durchs Wasser.\n Es geht über den Scheitel.\n Unheil. Kein Makel.",
  },
  {
    "number" : "29",
    "name-interpretation" : "Das Abgründige, das Wasser",
    "judgment" : "Das wiederholte Abgründige.\n Wenn du wahrhaftig bist, so hast du im Herzen Gelingen,\n und was du tust, hat Erfolg.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Wiederholung des Abgründigen.\n Man gerät im Abgrund in ein Loch. Unheil.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Der Abgrund hat Gefahr.\n Man soll nur Kleines zu erreichen streben.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Vorwärts und rückwärts, Abgrund über Abgrund.\n In solcher Gefahr halte zunächst inne,\n sonst kommst du im Abgrund in ein Loch.\n Handle nicht so.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Ein Krug Wein, eine Reisschale als Zugabe, Tongeschirr,\n einfach zum Fenster hineingereicht.\n Das ist durchaus kein Makel.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Der Abgrund wird nicht überfüllt,\n wird nur bis an den Rand gefüllt.\n Kein Makel.",
    "line-6" : "Oben eine Sechs bedeutet:\n Mit Stricken und Tauen gebunden,\n eingeschlossen zwischen dornumhegten Kerkermauern;\n drei Jahre lang findet man sich nicht zurecht.\n Unheil!",
  },
  {
    "number" : "30",
    "name-interpretation" : "Das Haftende, das Feuer",
    "judgment" : "Das Haftende. Fördernd ist Beharrlichkeit.\n Sie bringt Gelingen. Pflege der Kuh bringt Heil.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Die Fußspuren laufen kreuz und quer.\n Wenn man ernst dabei ist: kein Makel.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Gelber Schein. Erhabenes Heil.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Beim Schein der untergehenden Sonne\n schlagen die Menschen entweder auf den Topf und singen,\n oder sie seufzen laut über das nahende Greisenalter.\n Unheil.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Plötzlich ist sein Kommen;\n es brennt auf, erstirbt, wird weggeworfen.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Weinend in Strömen, seufzend und klagend. Heil!",
    "line-6" : "Oben eine Neun bedeutet:\n Der König gebraucht ihn, auszuziehen und zu züchtigen.\n Am besten ist es dann, die Häupter zu töten\n und die Nachläufer gefangen zu nehmen. Kein Makel.",
  },
  {
    "number" : "31",
    "name-interpretation" : "Die Einwirkung, (die Werbung)",
    "judgment" : "Die Einwirkung. Gelingen.\n Fördernd ist Beharrlichkeit.\n Ein Mädchen nehmen bringt Heil.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Die Einwirkung äußert sich in der großen Zehe.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Die Einwirkung äußert sich in den Waden. Unheil!\n Verweilen bringt Heil!",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Die Einwirkung äußert sich in den Schenkeln.\n Hält sich an das, was ihm folgt.\n Weitermachen ist beschämend.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Beharrlichkeit bringt Heil! Die Reue schwindet.\n Wenn man aufgeregt hin und her denkt,\n so folgen nur die Freunde,\n auf die man bewußte Gedanken richtet.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Die Einwirkung äußert sich im Nacken.\n Keine Reue.",
    "line-6" : "Oben eine Sechs bedeutet:\n Die Einwirkung äußert sich in Kinnladen,\n Wangen und Zunge.",
  },
  {
    "number" : "32",
    "name-interpretation" : "Die Dauer",
    "judgment" : "Gelingen. Kein Makel.\n Fördernd ist Beharrlichkeit.\n Fördernd ist, zu haben, wohin man gehe.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Zu rasch Dauer wollen, bringt beharrlich Unheil.\n Nichts, was fördernd wäre.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Reue schwindet.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Wer seinem Charakter nicht Dauer gibt,\n dem bietet man Schande.\n Beharrliche Beschämung.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Im Feld ist kein Wild.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Seinem Charakter Dauer geben durch Beharrlichkeit,\n das ist für eine Frau von Heil, für einen Mann von Unheil.",
    "line-6" : "Oben eine Sechs bedeutet:\n Rastlosigkeit als dauernder Zustand bringt Unheil.",
  },
  {
    "number" : "33",
    "name-interpretation" : "Der Rückzug",
    "judgment" : "Der Rückzug. Gelingen.\n Im Kleinen ist fördernd Beharrlichkeit.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Beim Rückzug am Schwanz: das ist gefährlich.\n Man darf nicht etwas unternehmen wollen.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Er hält ihn fest mit gelbem Ochsenleder.\n Niemand vermag ihn loszureißen.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Aufgehaltener Rückzug ist peinlich und gefahrvoll.\n Die Menschen als Knechte und Mägde zu halten, bringt Heil.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Freiwilliger Rückzug bringt dem Edlen Heil,\n dem Gemeinen Niedergang.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Freundlicher Rückzug. Beharrlichkeit bringt Heil.",
    "line-6" : "Oben eine Neun bedeutet:\n Heiterer Rückzug. Alles ist fördernd.",
  },
  {
    "number" : "34",
    "name-interpretation" : "Des Großen Macht",
    "judgment" : "Des Großen Macht. Fördernd ist Beharrlichkeit.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Macht in den Zehen.\n Fortmachen bringt Unheil.\n Das ist gewißlich wahr.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Beharrlichkeit bringt Heil.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Der Gemeine wirkt durch Macht, der Edle wirkt nicht so.\n Fortmachen ist gefährlich.\n Ein Ziegenbock stößt gegen eine Hecke\n und verwickelt seine Hörner.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Beharrlichkeit bringt Heil.\n Die Reue schwindet.\n Die Hecke öffnet sich, es gibt keine Verwicklung.\n Die Macht beruht auf der Achse eines großen Wagens.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Verliert den Bock in Leichtigkeit.\n Keine Reue.",
    "line-6" : "Oben eine Sechs bedeutet:\n Ein Bock stößt gegen eine Hecke:\n Er kann nicht zurück, er kann nicht voran.\n Nichts ist fördernd.\n Merkt man die Schwierigkeit, so bringt das Heil.",
  },
  {
    "number" : "35",
    "name-interpretation" : "Der Fortschritt",
    "judgment" : "Der Fortschritt:\n Der starke Fürst wird geehrt durch Pferde in großer Menge.\n An einem Tag wird er dreimal empfangen.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Fortschreitend, aber zurückgewiesen.\n Beharrlichkeit bringt Heil.\n Wenn man kein Vertrauen findet, so bleibe man gelassen.\n Kein Fehler.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Fortschreitend, aber in Trauer:\n Beharrlichkeit bringt Heil.\n Man bekommt dann großes Glück von seiner Ahnfrau.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Alle sind einverstanden. Die Reue schwindet.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Fortschritt wie ein Hamster.\n Beharrlichkeit bringt Gefahr.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Die Reue schwindet.\n Gewinn und Verlust nimm nicht zu Herzen.\n Unternehmungen bringen Heil.\n Alles ist fördernd.",
    "line-6" : "Oben eine Neun bedeutet:\n Fortschreiten mit den Hörnern darf man nur,\n um sein eigenes Gebiet zu strafen.\n Bewußtsein der Gefahr bringt Heil.\n Kein Makel.\n Beharrlichkeit bringt Beschämung.",
  },
  {
    "number" : "36",
    "name-interpretation" : "Die Verfinsterung des Lichts",
    "judgment" : "Die Verfinsterung des Lichts.\n Fördernd ist es, in der Not beharrlich zu sein.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Verfinsterung des Lichts im Fluge.\n Er senkt seine Flügel.\n Der Edle auf seiner Wanderschaft ißt drei Tage nichts.\n Aber er hat, wohin er geht.\n Der Wirt hat über ihn zu reden.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Die Verfinsterung des Lichts verletzt ihn am linken Schenkel.\n Er wirkt Hilfe mit der Macht eines Pferdes. Heil.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Die Verfinsterung des Lichts auf der Jagd im Süden.\n Man bekommt ihr großes Haupt.\n Man darf nicht zu eilig Beharrlichkeit erwarten.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Er dringt in die linke Bauchhöhle ein.\n Man erhält das Herz der Verfinsterung des Lichts\n und verläßt Tor und Hof.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Verfinsterung des Lichts wie beim Prinzen Gi.\n Fördernd ist Beharrlichkeit.",
    "line-6" : "Oben eine Sechs bedeutet:\n Nicht Licht, sondern Dunkel.\n Erst stieg er zum Himmel empor,\n dann stürzte er in die Tiefen der Erde hinunter.",
  },
  {
    "number" : "37",
    "name-interpretation" : "Die Sippe",
    "judgment" : "Die Sippe. Fördernd ist die Beharrlichkeit der Frau.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Fester Abschluß innerhalb der Sippe. Reue schwindet.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Sie soll nicht ihrer Laune folgen.\n Sie soll im Innern für Speise sorgen.\n Beharrlichkeit bringt Heil.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Wenn es in der Sippe hitzig zugeht,\n so entsteht Reue über zu große Strenge.\n Doch Heil!\n Wenn Weib und Kind tändeln und lachen,\n so führt das schließlich zu Beschämung.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Sie ist der Reichtum des Hauses.\n Großes Heil!",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Ein König naht er seiner Sippe, fürchtet euch nicht.\n Heil!",
    "line-6" : "Oben eine Neun bedeutet:\n Seine Arbeit ist ehrfurchtgebietend.\n Schließlich kommt Heil.",
  },
  {
    "number" : "38",
    "name-interpretation" : "Der Gegensatz",
    "judgment" : "Der Gegensatz. In kleinen Sachen Heil.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Die Reue schwindet.\n Wenn du dein Pferd verlierst, so lauf ihm nicht nach.\n Es kommt von selber wieder.\n Wenn du böse Menschen siehst, so hüte dich vor Fehlern.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Man begegnet seinem Herrn in enger Gasse.\n Kein Makel.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Man sieht den Wagen nach hinten gezerrt,\n die Rinder festgehalten,\n dem Menschen Haare und Nase abgeschnitten.\n Kein guter Anfang, aber ein gutes Ende.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Durch Gegensatz vereinsamt,\n trifft man einen Gleichgesinnten,\n mit dem man in Treue verkehren kann.\n Trotz der Gefahr kein Makel.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Die Reue schwindet.\n Der Gefährte beißt sich durch die Hülle.\n Wenn man hingeht zu ihm, wie wäre das ein Fehler?",
    "line-6" : "Oben eine Neun bedeutet:\n Durch Gegensatz vereinsamt, sieht man seinen Gefährten\n wie ein schmutzbeladenes Schwein,\n wie einen Wagen voll Teufel.\n Erst spannt man den Bogen nach ihm,\n dann legt man den Bogen weg.\n Nicht Räuber er ist, will freien zur Frist.\n Beim Hingehen fällt Regen, dann kommt Heil.",
  },
  {
    "number" : "39",
    "name-interpretation" : "Das Hemmnis",
    "judgment" : "Das Hemmnis. Fördernd ist der Südwesten.\n Nicht fördernd ist der Nordosten.\n Fördernd ist es, den großen Mann zu sehen.\n Beharrlichkeit ist von Heil.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Gehen führt in Hemmnisse, Kommen findet Lob.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Des Königs Diener ist in Hemmnis über Hemmnis.\n Aber es ist nicht seine eigene Schuld.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Gehen führt in Hemmnisse; da kommt er zurück.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Gehen führt in Hemmnisse,\n Kommen führt zur Vereinigung.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Inmitten der größten Hemmnisse kommen Freunde.",
    "line-6" : "Oben eine Sechs bedeutet:\n Gehen führt in Hemmnisse, Kommen führt zu großem Heil.\n Fördernd ist es, den großen Mann zu sehen.",
  },
  {
    "number" : "40",
    "name-interpretation" : "Die Befreiung",
    "judgment" : "Die Befreiung. Fördernd ist der Südwesten.\n Wenn nichts mehr da ist, wohin man zu gehen hätte,\n ist das Wiederkommen von Heil.\n Wenn es noch etwas gibt, wohin man gehen muß,\n dann ist Raschheit von Heil.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Ohne Makel.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Auf dem Feld erlegt man drei Füchse\n und bekommt einen gelben Pfeil.\n Beharrlichkeit ist von Heil.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Wenn einer eine Last auf dem Rücken trägt\n und trotzdem auf dem Wagen fährt,\n veranlaßt er dadurch die Räuber, herbeizukommen.\n Beharrlichkeit führt zu Beschämung.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Befreie dich von deiner großen Zehe.\n Dann kommt der Gefährte herbei,\n und dem kannst du trauen.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Wenn der Edle sich nur befreien kann, das bringt Heil.\n Er zeigt so den Gemeinen, daß es ihm ernst ist.",
    "line-6" : "Oben eine Sechs bedeutet:\n Der Fürst schießt nach einem Habicht auf hoher Mauer.\n Er erlegt ihn. Alles ist fördernd.",
  },
  {
    "number" : "41",
    "name-interpretation" : "Die Minderung",
    "judgment" : "Minderung verbunden mit Wahrhaftigkeit\n wirkt erhabenes Heil ohne Makel.\n Man kann darin beharrlich sein.\n Fördernd ist es, etwas zu unternehmen.\n Wie übt man das aus?\n Zwei kleine Schüsselchen mag man benützen zum Opfer.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Wenn die Geschäfte fertig sind, rasch hingehen\n ist kein Makel. Doch muß man überlegen,\n wie weit man andre mindern darf.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Fördernd ist Beharrlichkeit.\n Etwas zu unternehmen, ist von Unheil.\n Ohne sich selbst zu mindern,\n vermag man die andern zu mehren.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Wenn drei Menschen miteinander wandern,\n so vermindern sie sich um einen Menschen.\n Wenn ein Mensch wandert, so findet er seinen Gefährten.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Wenn man seine Mängel mindert macht man,\n daß der andre eilig kommt und Freude hat.\n Kein Makel.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Es mehrt ihn wohl jemand.\n Zehn Paar Schildkröten können dem nicht widerstreben.\n Erhabenes Heil!",
    "line-6" : "Oben eine Neun bedeutet:\n Wenn man ohne Minderung der anderen gemehrt wird,\n so ist das kein Makel. Beharrlichkeit bringt Heil.\n Fördernd ist es, etwas zu unternehmen.\n Man bekommt Diener, aber hat kein besonderes Heim mehr.",
  },
  {
    "number" : "42",
    "name-interpretation" : "Die Mehrung",
    "judgment" : "Die Mehrung. Fördernd ist es, etwas zu unternehmen.\n Fördernd ist es, das große Wasser zu durchqueren.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Fördernd ist es, große Taten zu vollbringen.\n Erhabenes Heil! Kein Makel.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Es mehrt ihn wohl jemand.\n Zehn Paar Schildkröten können dem nicht widerstreben.\n Dauernde Beharrlichkeit bringt Heil.\n Der König stellt ihn dar vor Gott. Heil!",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Man wird gemehrt durch unheilvolle Ereignisse.\n Kein Makel, wenn du wahrhaftig bist\n und in der Mitte wandelst\n und dem Fürsten berichtest mit einem Siegel.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Wenn du in der Mitte wandelst\n und dem Fürsten berichtest,\n so wird er folgen.\n Fördernd ist es, benützt zu werden\n bei der Verlegung der Hauptstadt.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Wenn du wahrhaftig ein gütiges Herz hast,\n so frage nicht. Erhabenes Heil!\n Wahrhaftig wird Güte als deine Tugend erkannt werden.",
    "line-6" : "Oben eine Neun bedeutet:\n Er gereicht niemand zur Mehrung.\n Es schlägt ihn wohl gar jemand.\n Er hält sein Herz nicht dauernd fest. Unheil!",
  },
  {
    "number" : "43",
    "name-interpretation" : "Der Durchbruch, (die Entschlossenheit)",
    "judgment" : "Der Durchbruch.\n Entschlossen muß man am Hof des Königs die Sache bekanntmachen.\n Der Wahrheit gemäß muß sie verkündet werden. Gefahr!\n Man muß seine eigene Stadt benachrichtigen.\n Nicht fördernd ist es, zu den Waffen zu greifen.\n Fördernd ist es, etwas zu unternehmen.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Mächtig in den vorwärtsschreitenden Zehen.\n Geht man hin und ist der Sache nicht gewachsen,\n so macht man einen Fehler.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Alarmruf. Abends und nachts Waffen.\n Fürchte nichts.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Mächtig in den Backenknochen zu sein bringt Unheil.\n Der Edle ist fest entschlossen.\n Er wandelt einsam und kommt in den Regen.\n Er wird bespritzt, und man murrt wider ihn.\n Kein Makel.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n An den Oberschenkeln ist keine Haut,\n und das Gehen fällt schwer.\n Ließe man sich führen wie ein Schaf,\n so würde die Reue schwinden.\n Wenn man aber diese Worte hört,\n so wird man sie nicht glauben.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Dem Unkraut gegenüber braucht es feste Entschlossenheit.\n In der Mitte wandeln bleibt frei von Makel.",
    "line-6" : "Oben eine Sechs bedeutet:\n Kein Ruf! Schließlich kommt Unheil.",
  },
  {
    "number" : "44",
    "name-interpretation" : "Das Entgegenkommen",
    "judgment" : "Das Entgegenkommen. Das Mädchen ist mächtig.\n Man soll ein solches Mädchen nicht heiraten.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Man muß es hemmen mit ehernem Radschuh.\n Beharrlichkeit ist von Heil.\n Wenn man es hingehen läßt, so erfährt man Unheil.\n Auch ein mageres Schwein hat die Anlage dazu, umherzutoben.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Im Behälter ist ein Fisch. Kein Makel!\n Nicht fördernd für Gäste.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n An den Oberschenkeln ist keine Haut,\n und das Gehen fällt schwer.\n Wenn man der Gefahr eingedenk ist,\n macht man keinen großen Fehler.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Im Behälter ist kein Fisch.\n Daraus erhebt sich Unheil.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Mit Weidenblättern bedeckte Melone:\n verborgene Linien.\n Da fällt es einem vom Himmel herunter zu.",
    "line-6" : "Oben eine Neun bedeutet:\n Er kommt mit seinen Hörnern entgegen.\n Beschämung. Kein Makel.",
  },
  {
    "number" : "45",
    "name-interpretation" : "Die Sammlung",
    "judgment" : "Die Sammlung. Gelingen.\n Der König naht sich seinem Tempel.\n Fördernd ist es, den großen Mann zu sehen.\n Das bringt Gelingen. Fördernd ist Beharrlichkeit.\n Große Opfer zu bringen schafft Heil.\n Fördernd ist es, etwas zu unternehmen.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Wenn du wahrhaftig bist, doch nicht bis zum Ende,\n so gibt es bald Verwirrung, bald Sammlung.\n Wenn du rufst, so kannst du nach einem Griff wieder lachen.\n Bedauere nicht. Hingehen ist ohne Makel.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Sich ziehen lassen bringt Heil und bleibt ohne Makel.\n Wenn man wahrhaftig ist,\n so ist es auch fördernd, ein kleines Opfer zu bringen.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Sammlung unter Seufzen. Nichts, das fördernd wäre.\n Hingehen ist ohne Makel. Kleine Beschämung.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Großes Heil! Kein Makel.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Wenn man beim Sammeln die nötige Stellung hat,\n so gibt es keinen Makel.\n Wenn manche noch nicht wahrhaft dabei sind,\n so bedarf es erhabener, dauernder Beharrlichkeit,\n dann schwindet die Reue.",
    "line-6" : "Oben eine Sechs bedeutet:\n Klagen und Seufzen, Tränen in Strömen! Kein Makel.",
  },
  {
    "number" : "46",
    "name-interpretation" : "Das Empordringen",
    "judgment" : "Das Empordringen hat erhabenes Gelingen.\n Man muß den großen Mann sehen.\n Fürchte dich nicht!\n Aufbruch nach Süden bringt Heil.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Empordringen, das Zutrauen findet, bringt großes Heil.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Wenn man wahrhaftig ist,\n so ist es fördernd, ein kleines Opfer zu bringen.\n Kein Makel.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Man dringt empor in eine leere Stadt.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Der König bringt ihn dem Berg Ki dar. Heil. Kein Makel.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Beharrlichkeit bringt Heil. Man dringt empor auf Stufen.",
    "line-6" : "Oben eine Sechs bedeutet:\n Empordringen im Dunkeln.\n Fördernd ist es, unablässig beharrlich zu sein.",
  },
  {
    "number" : "47",
    "name-interpretation" : "Die Bedrängnis, (die Erschöpfung)",
    "judgment" : "Die Bedrängnis. Gelingen. Beharrlichkeit.\n Der große Mann wirkt Heil. Kein Makel.\n Wenn man etwas zu sagen hat, wird es nicht geglaubt.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Man sitzt bedrängt unter einem kahlen Baum\n und gerät in ein finsteres Tal.\n Drei Jahre lang sieht man nichts.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Man ist bedrängt bei Wein und Speisen.\n Der Mann mit den scharlachroten Kniebinden kommt eben.\n Fördernd ist es, Opfer darzubringen.\n Aufbrechen ist von Unheil.\n Kein Makel.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Man läßt sich bedrängen durch Stein\n und stützt sich auf Dornen und Disteln.\n Man geht in sein Haus und sieht nicht seine Frau. Unheil!",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Er kommt ganz sachte, bedrängt in einem goldenen Wagen.\n Beschämung, aber man kommt zu Ende.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Es werden ihm Nase und Füße abgeschnitten.\n Man ist bedrängt von dem in purpurnen Kniebinden.\n Sachte kommt die Freude.\n Fördernd ist es, Opfer und Spenden zu bringen.",
    "line-6" : "Oben eine Sechs bedeutet:\n Er ist bedrängt von Ranken.\n Er bewegt sich unsicher und spricht:\n „Bewegung schafft Reue.“\n Wenn man darüber Reue empfindet und sich aufmacht,\n so hat man Heil.",
  },
  {
    "number" : "48",
    "name-interpretation" : "Der Brunnen",
    "judgment" : "Der Brunnen. Man mag die Stadt wechseln,\n aber kann nicht den Brunnen wechseln.\n Er nimmt nicht ab und nimmt nicht zu.\n Sie kommen und gehen und schöpfen aus dem Brunnen.\n Wenn man beinahe das Brunnenwasser erreicht hat,\n aber noch nicht mit dem Seil drunten ist\n oder seinen Krug zerbricht, so bringt das Unheil.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Der Schlamm des Brunnens wird nicht getrunken:\n zu einem alten Brunnen kommen keine Tiere.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Am Brunnenloch schießt man Fische.\n Der Krug ist zerbrochen und rinnt.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Der Brunnen ist gereinigt, aber man trinkt nicht daraus.\n Das ist meines Herzens Leid;\n denn man könnte daraus schöpfen.\n Wäre der König klar, so genösse man gemeinsam das Glück.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Der Brunnen wird ausgemauert, kein Makel.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Im Brunnen ist ein klarer, kühler Quell, den man trinken kann.",
    "line-6" : "Oben eine Sechs bedeutet:\n Man schöpft aus dem Brunnen ohne Hinderung.\n Er ist zuverlässig. Erhabenes Heil!",
  },
  {
    "number" : "49",
    "name-interpretation" : "Die Umwälzung, (die Mauserung)",
    "judgment" : "Die Umwälzung.\n Am eigenen Tag, da findest du Glauben.\n Erhabenes Gelingen, fördernd durch Beharrlichkeit.\n Die Reue schwindet.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Man wird eingewickelt in das Fell einer gelben Kuh.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Am eigenen Tag, da mag man umwälzen.\n Aufbruch bringt Heil. Kein Makel.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Aufbruch bringt Unheil. Beharrlichkeit bringt Gefahr.\n Wenn die Rede von der Umwälzung dreimal ergangen ist,\n dann mag man sich ihr zuwenden und wird Glauben finden.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Die Reue schwindet. Man findet Glauben.\n Die Staatsordnung zu wechseln bringt Heil.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Der große Mann ändert wie ein Tiger.\n Noch ehe er das Orakel fragt, findet er Glauben.",
    "line-6" : "Oben eine Sechs bedeutet:\n Der Edle ändert wie ein Panther.\n Der Geringe mausert sich im Gesicht.\n Aufbruch bringt Unheil.\n In Beharrlichkeit weilen bringt Heil.",
  },
  {
    "number" : "50",
    "name-interpretation" : "Der Tiegel",
    "judgment" : "Der Tiegel. Erhabenes Heil. Gelingen.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Ein Tiegel mit umgekippten Beinen.\n Fördernd zur Entfernung des Stockenden.\n Man nimmt eine Nebenfrau um ihres Sohns willen.\n Kein Makel.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Im Tiegel ist Nahrung.\n Meine Genossen haben Neid,\n aber sie können mir nichts anhaben.\n Heil!",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Der Henkel des Tiegels ist verändert.\n Man ist behindert in seinem Wandel.\n Das Fett des Fasans wird nicht gegessen.\n Wenn erst der Regen fällt, dann erschöpft sich die Reue:\n Endlich kommt Heil.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Der Tiegel bricht die Beine.\n Das Mahl des Fürsten wird verschüttet,\n und die Gestalt wird befleckt.\n Unheil!",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Der Tiegel hat gelbe Henkel, goldne Tragringe.\n Fördernd ist Beharrlichkeit.",
    "line-6" : "Oben eine Neun bedeutet:\n Der Tiegel hat Nephritringe. Großes Heil!\n Nichts, das nicht fördernd wäre.",
  },
  {
    "number" : "51",
    "name-interpretation" : "Das Erregende, (das Erschüttern, der Donner)",
    "judgment" : "Das Erschüttern bringt Gelingen.\n Das Erschüttern kommt: Hu, Hu!\n Lachende Worte: Ha, Ha!\n Das Erschüttern erschreckt hundert Meilen,\n und er läßt nicht Opferlöffel und Kelch fallen.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Das Erschüttern kommt: Hu, Hu!\n Darauf folgen lachende Worte: Ha, Ha!\n Heil!",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Das Erschüttern kommt mit Gefahr.\n Hunderttausendfach verlierst du deine Schätze\n und mußt auf die neun Hügel steigen.\n Jage ihnen nicht nach.\n Nach sieben Tagen bekommst du sie wieder.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Das Erschüttern kommt und macht fassungslos.\n Wenn man infolge des Erschütterns handelt,\n so bleibt man frei von Unglück.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Das Erschüttern gerät in Schlamm.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Das Erschüttern geht hin und her: Gefahr.\n Aber man verliert durchaus nichts,\n nur gibt es Geschäfte.",
    "line-6" : "Oben eine Sechs bedeutet:\n Die Erschütterung bringt Verfall und ängstliches Umherblicken.\n Vorangehen bringt Unheil.\n Wenn sie noch nicht den eignen Leib erreicht,\n sondern erst den Nachbar erreicht hat,\n so ist es kein Makel.\n Die Genossen haben zu reden.",
  },
  {
    "number" : "52",
    "name-interpretation" : "Das Stillehalten, der Berg",
    "judgment" : "Stillehalten seines Rückens,\n so daß er seinen Leib nicht mehr empfindet.\n Er geht in seinen Hof und sieht nicht seine Menschen.\n Kein Makel.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Stillehalten seiner Zehen.\n Kein Makel. Fördernd ist dauernde Beharrlichkeit.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Stillehalten seiner Waden.\n Er kann den nicht retten, dem er folgt.\n Sein Herz ist nicht froh.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Stillehalten seiner Hüften.\n Steifmachen seines Kreuzbeins.\n Gefährlich. Das Herz erstickt.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Stillehalten seines Rumpfes.\n Kein Makel.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Stillehalten seiner Kinnladen.\n Die Worte haben Ordnung.\n Die Reue schwindet.",
    "line-6" : "Oben eine Neun bedeutet:\n Großzügiges Stillehalten. Heil!",
  },
  {
    "number" : "53",
    "name-interpretation" : "Die Entwicklung, (allmählicher Fortschritt)",
    "judgment" : "Die Entwicklung. Das Mädchen wird verheiratet. Heil!\n Fördernd ist Beharrlichkeit.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Die Wildgans zieht allmählich dem Ufer zu.\n Der junge Sohn ist in Gefahr.\n Es gibt Gerede. Kein Makel.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Die Wildgans zieht allmählich dem Felsen zu.\n Essen und Trinken in Frieden und Eintracht. Heil!",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Die Wildgans zieht allmählich der Hochebene zu.\n Der Mann zieht aus und kehrt nicht wieder.\n Die Frau trägt ein Kind, aber bringt es nicht zur Welt.\n Unheil!\n Fördernd ist es, Räuber abzuwehren.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Die Wildgans zieht allmählich dem Baume zu.\n Vielleicht bekommt sie einen flachen Ast. Kein Makel.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Die Wildgans zieht allmählich dem Gipfel zu.\n Die Frau bekommt drei Jahre lang kein Kind.\n Endlich kann sie nichts verhindern. Heil!",
    "line-6" : "Oben eine Neun bedeutet:\n Die Wildgans zieht allmählich den Wolkenhöhen zu.\n Ihre Federn können zum heiligen Tanz verwendet werden.\n Heil!",
  },
  {
    "number" : "54",
    "name-interpretation" : "Das heiratende Mädchen",
    "judgment" : "Das heiratende Mädchen.\n Unternehmungen bringen Unheil.\n Nichts, das fördernd wäre.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Das heiratende Mädchen als Nebenfrau.\n Ein Lahmer, der auftreten kann.\n Unternehmungen bringen Heil.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Ein Einäugiger, der sehen kann.\n Fördernd ist die Beharrlichkeit eines einsamen Menschen.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Das heiratende Mädchen als Sklavin.\n Sie heiratet als Nebenfrau.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Das heiratende Mädchen verzögert die Frist.\n Eine späte Heirat kommt zu ihrer Zeit.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Der Herrscher I verheiratet seine Tochter.\n Da waren die gestickten Kleider der Fürstin nicht so\n prächtig wie die Kleider der Dienerin.\n Der Mond, der fast voll ist, bringt Heil.",
    "line-6" : "Oben eine Sechs bedeutet:\n Die Frau hält den Korb, aber es sind keine Früchte darin.\n Der Mann sticht das Schaf, aber es fließt kein Blut.\n Nichts, das fördernd wäre.",
  },
  {
    "number" : "55",
    "name-interpretation" : "Die Fülle",
    "judgment" : "Die Fülle hat Gelingen.\n Der König erreicht sie.\n Sei nicht traurig; du mußt sein wie die Sonne am Mittag.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Wenn man seinem bestimmten Herrn begegnet,\n so mag man zehn Tage beisammen sein,\n und es ist kein Fehler.\n Hingehen findet Anerkennung.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Der Vorhang ist von solcher Fülle,\n daß man am Mittag die Polsterne sieht.\n Durch Hingehen erreicht man Mißtrauen und Haß.\n Wenn man durch Wahrheit ihn erweckt, kommt Heil.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Das Gestrüpp ist von solcher Fülle,\n daß man am Mittag die kleinen Sterne sieht.\n Er bricht seinen rechten Arm. Kein Makel.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Der Vorhang ist von solcher Fülle,\n daß man am Mittag die Polsterne sieht.\n Er begegnet seinem gleichen Herrn. Heil!",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Es kommen Linien, es naht Segen und Ruhm. Heil!",
    "line-6" : "Oben eine Sechs bedeutet:\n Sein Haus ist in Fülle.\n Er verdeckt seine Sippe.\n Er späht durch das Tor und merkt niemand mehr.\n Drei Jahre lang sieht er nichts. Unheil!",
  },
  {
    "number" : "56",
    "name-interpretation" : "Der Wanderer",
    "judgment" : "Der Wanderer. Durch Kleinheit Gelingen.\n Dem Wanderer ist Beharrlichkeit von Heil.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Wenn der Wanderer sich mit kleinlichen Dingen abgibt,\n so zieht er sich dadurch Unglück zu.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Der Wanderer kommt zur Herberge.\n Er hat seinen Besitz bei sich.\n Er erlangt eines jungen Dieners Beharrlichkeit.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Dem Wanderer verbrennt seine Herberge.\n Er verliert die Beharrlichkeit seines jungen Dieners.\n Gefahr.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Der Wanderer ruht an einem Unterkunftsort.\n Er erlangt seinen Besitz und eine Axt.\n Mein Herz ist nicht froh.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Er schießt einen Fasan, auf den ersten Pfeil fällt er.\n Schließlich kommt dadurch Lob und Amt.",
    "line-6" : "Oben eine Neun bedeutet:\n Dem Vogel verbrennt sein Nest.\n Der Wanderer lacht erst,\n dann muß er klagen und weinen.\n Er verliert die Kuh im Leichtsinn. Unheil!",
  },
  {
    "number" : "57",
    "name-interpretation" : "Das Sanfte, (das Eindringliche, der Wind)",
    "judgment" : "Das Sanfte. Durch Kleines Gelingen.\n Fördernd ist es, zu haben, wohin man geht.\n Fördernd ist es, den großen Mann zu sehen.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Beim Vorgehen und Rückweichen\n ist fördernd die Beharrlichkeit eines Kriegers.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Eindringen unter das Bett.\n Man benützt Priester und Magier in großer Zahl.\n Heil! Kein Makel.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Wiederholtes Eindringen. Beschämung.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Reue schwindet.\n Auf der Jagd fangt man drei Arten von Wild.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Beharrlichkeit bringt Heil. Reue schwindet.\n Nichts, das nicht fördernd ist.\n Kein Anfang, aber ein Ende.\n Vor der Änderung drei Tage,\n nach der Änderung drei Tage. Heil!",
    "line-6" : "Oben eine Neun bedeutet:\n Eindringen unter das Bett.\n Er verliert seinen Besitz und seine Axt.\n Beharrlichkeit bringt Unheil.",
  },
  {
    "number" : "58",
    "name-interpretation" : "Das Heitere, der See",
    "judgment" : "Das Heitere. Gelingen. Günstig ist Beharrlichkeit.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Zufriedene Heiterkeit. Heil!",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Wahrhaftige Heiterkeit. Heil! Die Reue schwindet.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Kommende Heiterkeit. Unheil!",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Überlegte Heiterkeit ist nicht beruhigt.\n Nach Abtun der Fehler hat man Freude.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Wahrhaftigkeit gegen das Zersetzende ist gefährlich.",
    "line-6" : "Oben eine Sechs bedeutet:\n Verführende Heiterkeit.",
  },
  {
    "number" : "59",
    "name-interpretation" : "Die Auflösung",
    "judgment" : "Die Auflösung. Gelingen.\n Der König naht seinem Tempel.\n Fördernd ist es, das große Wasser zu durchqueren.\n Fördernd ist Beharrlichkeit.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Er bringt Hilfe mit der Macht eines Pferdes. Heil!",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Bei der Auflösung läuft er seiner Stütze zu.\n Die Reue schwindet.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Er löst sein Ich auf. Keine Reue.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Er löst sich von seiner Schar. Erhabenes Heil!\n Durch Auflösung folgt Anhäufung.\n Das ist etwas, an das Gewöhnliche nicht denken.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Auflösend wie Schweiß sind seine lauten Rufe.\n Auflösung! Ein König weilt ohne Makel.",
    "line-6" : "Oben eine Neun bedeutet:\n Er löst sein Blut auf.\n Weggehen, sich fernhalten, hinausgehen ist ohne Makel.",
  },
  {
    "number" : "60",
    "name-interpretation" : "Die Beschränkung",
    "judgment" : "Beschränkung. Gelingen.\n Bittere Beschränkung darf man nicht beharrlich üben.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Nicht zu Tür und Hof hinausgehen ist kein Makel.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Nicht zu Tor und Hof hinausgehen bringt Unheil.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Wer keine Beschränkung kennt, wird zu klagen haben.\n Kein Makel.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Zufriedene Beschränkung. Gelingen.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Süße Beschränkung bringt Heil.\n Hingehen bringt Achtung.",
    "line-6" : "Oben eine Sechs bedeutet:\n Bittere Beschränkung: Beharrlichkeit bringt Unheil.\n Reue schwindet.",
  },
  {
    "number" : "61",
    "name-interpretation" : "Innere Wahrheit",
    "judgment" : "Innere Wahrheit. Schweine und Fische. Heil!\n Fördernd ist es, das große Wasser zu durchqueren.\n Fördernd ist Beharrlichkeit.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Bereit sein bringt Heil.\n Sind Hintergedanken da, so ist das beunruhigend.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Ein rufender Kranich im Schatten.\n Sein Junges antwortet ihm.\n Ich habe einen guten Becher. Ich will ihn mit dir teilen.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Er findet einen Genossen,\n bald trommelt er, bald hört er auf.\n Bald schluchzt er, bald singt er.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Der Mond, der beinahe voll ist.\n Das Gespannpferd geht verloren.\n Kein Makel.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Er besitzt Wahrheit, die verkettet.\n Kein Makel.",
    "line-6" : "Oben eine Neun bedeutet:\n Hahnenruf, der zum Himmel dringt.\n Beharrlichkeit bringt Unheil.",
  },
  {
    "number" : "62",
    "name-interpretation" : "Des Kleinen Übergewicht",
    "judgment" : "Des Kleinen Übergewicht. Gelingen.\n Fördernd ist Beharrlichkeit.\n Man mag kleine Dinge tun, man soll nicht große Dinge tun.\n Der fliegende Vogel bringt die Botschaft:\n Es ist nicht gut, nach oben zu streben,\n es ist gut, unten zu bleiben. Großes Heil!",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Der Vogel kommt durch Fliegen ins Unheil.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Sie geht an ihrem Ahnherrn vorbei und trifft die Ahnfrau.\n Er erreicht nicht seinen Fürsten und trifft den Beamten.\n Kein Makel.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Wenn man sich nicht außerordentlich vorsieht,\n so kommt etwa einer von hinten und schlägt einen.\n Unheil!",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Kein Makel. Ohne vorbeizugehen, trifft er ihn.\n Hingehen bringt Gefahr. Man muß sich hüten.\n Handle nicht. Sei dauernd beharrlich.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Dichte Wolken, kein Regen von unserm westlichen Gebiet.\n Der Fürst schießt und trifft jenen in der Höhle.",
    "line-6" : "Oben eine Sechs bedeutet:\n Ohne ihn zu treffen, geht er an ihm vorbei.\n Der fliegende Vogel verläßt ihn. Unheil!\n Das bedeutet Unglück und Schaden.",
  },
  {
    "number" : "63",
    "name-interpretation" : "Nach der Vollendung",
    "judgment" : "Gelingen im Kleinen. Fördernd ist Beharrlichkeit.\n Im Anfang Heil, am Ende Wirren.",
    "line-1" : "Anfangs eine Neun bedeutet:\n Er hemmt seine Räder.\n Er kommt mit dem Schwanz ins Wasser.\n Kein Makel.",
    "line-2" : "Sechs auf zweitem Platz bedeutet:\n Die Frau verliert ihren Wagenvorhang.\n Lauf ihm nicht nach. Am siebenten Tag bekommst du ihn.",
    "line-3" : "Neun auf drittem Platz bedeutet:\n Der hohe Ahn züchtigt das Teufelsland.\n Nach drei Jahren überwindet er es.\n Gemeine darf man nicht verwenden.",
    "line-4" : "Sechs auf viertem Platz bedeutet:\n Die schönsten Kleider geben Lumpen.\n Den ganzen Tag sei vorsichtig.",
    "line-5" : "Neun auf fünftem Platz bedeutet:\n Der Nachbar im Osten, der einen Ochsen schlachtet,\n bekommt nicht soviel wirkliches Glück\n wie der Nachbar im Westen mit seinem kleinen Opfer.",
    "line-6" : "Oben eine Sechs bedeutet:\n Er kommt mit dem Haupt ins Wasser. Gefahr.",
  },
  {
    "number" : "64",
    "name-interpretation" : "Vor der Vollendung",
    "judgment" : "Vor der Vollendung. Gelingen.\n Wenn aber der kleine Fuchs,\n wenn er beinahe den Übergang vollendet hat,\n mit dem Schwanz ins Wasser kommt,\n dann ist nichts, das fördernd wäre.",
    "line-1" : "Anfangs eine Sechs bedeutet:\n Er kommt mit dem Schwanz ins Wasser.\n Beschämend.",
    "line-2" : "Neun auf zweitem Platz bedeutet:\n Er hemmt seine Räder.\n Beharrlichkeit bringt Heil.",
    "line-3" : "Sechs auf drittem Platz bedeutet:\n Vor der Vollendung bringt Angriff Unheil.\n Fördernd ist es, das große Wasser zu durchqueren.",
    "line-4" : "Neun auf viertem Platz bedeutet:\n Beharrlichkeit bringt Heil. Reue schwindet.\n Erschütterung, um das Teufelsland zu züchtigen.\n Drei Jahre lang gibt es Belohnung mit großen Reichen.",
    "line-5" : "Sechs auf fünftem Platz bedeutet:\n Beharrlichkeit bringt Heil. Keine Reue.\n Das Licht des Edlen ist wahrhaftig.\n Heil!",
    "line-6" : "Oben eine Neun bedeutet:\n In wahrem Vertrauen trinkt man Wein.\n Kein Makel. Wenn man aber sein Haupt naß macht,\n so verliert man das in Wahrheit.",
  },
]
}
}
