export class ChangesText {
static get name() { return "wilhelm-baynes" }
static get edition() { return "text-wilhelm-baynes.xml" }
static get version() { return "2018-06-04-17-39-58" }
static get changes() { return [
  {
    "number" : "1",
    "name-interpretation" : "The Creative",
    "judgment" : "THE CREATIVE works sublime success,\n Furthering through perseverance.",
    "line-1" : "Nine at the beginning means:\n Hidden dragon. Do not act.",
    "line-2" : "Nine in the second place means:\n Dragon appearing in the field.\n It furthers one to see the great man.",
    "line-3" : "Nine in the third place means:\n All day long the superior man is creatively active.\n At nightfall his mind is still beset with cares.\n Danger. No blame.",
    "line-4" : "Nine in the fourth place means:\n Wavering flight over the depths.\n No blame.",
    "line-5" : "Nine in the fifth place means:\n Flying dragon in the heavens.\n It furthers one to see the great man.",
    "line-6" : "Nine at the top means:\n Arrogant dragon will have cause to repent.",
    "line-7" : "When all the lines are nines, it means:\n There appears a flight of dragons without heads.\n Good fortune.",
  },
  {
    "number" : "2",
    "name-interpretation" : "The Receptive",
    "judgment" : "THE RECEPTIVE brings about sublime success,\n Furthering through the perseverance of a mare.\n If the superior man undertakes something and tries to lead,\n He goes astray;\n But if he follows, he finds guidance.\n It is favorable to find friends in the west and south,\n To forego friends in the east and north.\n Quiet perseverance brings good fortune.",
    "line-1" : "Six at the beginning means:\n When there is hoarfrost underfoot,\n Solid ice is not far off.",
    "line-2" : "Six in the second place means:\n Straight, square, great.\n Without purpose,\n Yet nothing remains unfurthered.",
    "line-3" : "Six in the third place means:\n Hidden lines.\n One is able to remain persevering.\n If by chance you are in the service of a king,\n Seek not works, but bring to completion.",
    "line-4" : "Six in the fourth place means:\n A tied-up sack. No blame, no praise.",
    "line-5" : "Six in the fifth place means:\n A yellow lower garment brings supreme good fortune.",
    "line-6" : "Six at the top means:\n Dragons fight in the meadow.\n Their blood is black and yellow.",
    "line-7" : "When all the lines are sixes, it means:\n Lasting perseverance furthers.",
  },
  {
    "number" : "3",
    "name-interpretation" : "Difficulty at the Beginning",
    "judgment" : "DIFFICULTY AT THE BEGINNING works supreme success,\n Furthering through perseverance.\n Nothing should be undertaken.\n It furthers one to appoint helpers.",
    "line-1" : "Nine at the beginning means:\n Hesitation and hindrance.\n It furthers one to remain persevering.\n It furthers one to appoint helpers.",
    "line-2" : "Six in the second place means:\n Difficulties pile up.\n Horse and wagon part.\n He is not a robber;\n He wants to woo when the time comes.\n The maiden is chaste,\n She does not pledge herself.\n Ten years--then she pledges herself.",
    "line-3" : "Six in the third place means:\n Whoever hunts deer without the forester\n Only loses his way in the forest.\n The superior man understands the signs of the time\n And prefers to desist.\n To go on brings humiliation.",
    "line-4" : "Six in the fourth place means:\n Horse and wagon part.\n Strive for union.\n To go brings good fortune.\n Everything acts to further.",
    "line-5" : "Nine in the fifth place means:\n Difficulties in blessing.\n A little perseverance brings good fortune.\n Great perseverance brings misfortune.",
    "line-6" : "Six at the top means:\n Horse and wagon part.\n Bloody tears flow.",
  },
  {
    "number" : "4",
    "name-interpretation" : "Youthful Folly",
    "judgment" : "YOUTHFUL FOLLY has success.\n It is not I who seek the young fool;\n The young fool seeks me.\n At the first oracle I inform him.\n If he asks two or three times, it is importunity.\n If he importunes, I give him no information.\n Perseverance furthers.",
    "line-1" : "Six at the beginning means:\n To make a fool develop\n It furthers one to apply discipline.\n The fetters should be removed.\n To go on in this way bring humiliation.",
    "line-2" : "Nine in the second place means:\n To bear with fools in kindliness brings good fortune.\n To know how to take women\n Brings good fortune.\n The son is capable of taking charge of the household.",
    "line-3" : "Six in the third place means:\n Take not a maiden who. When she sees a man of bronze,\n Loses possession of herself.\n Nothing furthers.",
    "line-4" : "Six in the fourth place means:\n Entangled folly bring humiliation.",
    "line-5" : "Six in the fifth place means:\n Childlike folly brings good fortune.",
    "line-6" : "Nine at the top means:\n In punishing folly\n It does not further one\n To commit transgressions.\n The only thing that furthers\n Is to prevent transgressions.",
  },
  {
    "number" : "5",
    "name-interpretation" : "Waiting (Nourishment)",
    "judgment" : "WAITING. If you are sincere,\n You have light and success.\n Perseverance brings good fortune.\n It furthers one to cross the great water.",
    "line-1" : "Nine at the beginning means:\n Waiting in the meadow.\n IT furthers one to abide in what endures.\n No blame.",
    "line-2" : "Nine in the second place means:\n Waiting on the sand.\n There is some gossip.\n The end brings good fortune.",
    "line-3" : "Nine in the third place means:\n Waiting in the mud\n Brings about the arrival of the enemy.",
    "line-4" : "Six in the fourth place means:\n Waiting in blood.\n Get out of the pit.",
    "line-5" : "Nine in the fifth place means:\n Waiting at meat and drink.\n Perseverance brings good fortune.",
    "line-6" : "Six at the top means:\n One falls into the pit.\n Three uninvited guests arrive.\n Honor them, and in the end there will be good fortune.",
  },
  {
    "number" : "6",
    "name-interpretation" : "Conflict",
    "judgment" : "CONFLICT. You are sincere\n And are being obstructed.\n A cautious halt halfway brings good fortune.\n Going through to the end brings misfortune.\n It furthers one to see the great man.\n It does not further one to cross the great water.",
    "line-1" : "Six at the beginning means:\n If one does not perpetuate the affair,\n There is a little gossip.\n In the end, good fortune comes.",
    "line-2" : "Nine in the second place means:\n One cannot engage in conflict;\n One returns home, gives way.\n The people of his town,\n Three hundred households,\n Remain free of guilt.",
    "line-3" : "Six in the third place means:\n To nourish oneself on ancient virtue induces perseverance.\n Danger. In the end, good fortune comes.\n If by chance you are in the service of a king,\n Seek not works.",
    "line-4" : "Nine in the fourth place means:\n One cannot engage in conflict.\n One turns back and submits to fate,\n Changes one's attitude,\n And finds peace in perseverance.\n Good fortune.",
    "line-5" : "Nine in the fifth place means:\n To contend before him\n Brings supreme good fortune.",
    "line-6" : "Nine at the top means:\n Even if by chance a leather belt is bestowed on one,\n By the end of a morning\n It will have been snatched away three times.",
  },
  {
    "number" : "7",
    "name-interpretation" : "The Army",
    "judgment" : "THE ARMY. The army needs perseverance\n And a strong man.\n Good fortune without blame.",
    "line-1" : "Six at the beginning means:\n An army must set forth in proper order.\n If the order is not good, misfortune threatens.",
    "line-2" : "Nine in the second place means:\n In the midst of the army.\n Good fortune. No blame.\n The king bestows a triple decoration.",
    "line-3" : "Six in the third place means:\n Perchance the army carries corpses in the wagon.\n Misfortune.",
    "line-4" : "Six in the fourth place means:\n The army retreats. No blame.",
    "line-5" : "Six in the fifth place means:\n There is game in the field.\n It furthers one to catch it.\n Without blame.\n Let the eldest lead the army.\n The younger transports corpses;\n Then perseverance brings misfortune.",
    "line-6" : "Six at the top means:\n The great prince issues commands,\n Founds states, vests families with fiefs.\n Inferior people should not be employed.",
  },
  {
    "number" : "8",
    "name-interpretation" : "Holding Together [Union]",
    "judgment" : "HOLDING TOGETHER brings good fortune.\n Inquire of the oracle once again\n Whether you possess sublimity, constancy, and perseverance;\n Then there is no blame.\n Those who are uncertain gradually join.\n Whoever comes too late\n Meets with misfortune.",
    "line-1" : "Six at the beginning means:\n Hold to him in truth and loyalty;\n This is without blame.\n Truth, like a full earthen bowl.\n Thus in the end\n Good fortune comes from without.",
    "line-2" : "Six in the second place means:\n Hold to him inwardly.\n Perseverance brings good fortune.",
    "line-3" : "Six in the third place means:\n You hold together with the wrong people.",
    "line-4" : "Six in the fourth place means:\n Hold to him outwardly also.\n Perseverance brings good fortune.",
    "line-5" : "Nine in the fifth place means:\n Manifestation of holding together.\n In the hunt the king uses beaters on three sides only\n And forgoes game that runs off in front.\n The citizens need no warning.\n Good fortune.",
    "line-6" : "Six at the top means:\n He finds no head for holding together.\n Misfortune.",
  },
  {
    "number" : "9",
    "name-interpretation" : "The Taming Power of the Small",
    "judgment" : "THE TAMING POWER OF THE SMALL\n Has success.\n Dense clouds, no rain from our western region.",
    "line-1" : "Nine at the beginning means:\n Return to the way.\n How could there be blame in this?\n Good fortune.",
    "line-2" : "Nine in the second place means:\n He allows himself to be drawn into returning.\n Good fortune.",
    "line-3" : "Nine in the third place means:\n The spokes burst out of the wagon wheels.\n Man and wife roll their eyes.",
    "line-4" : "Six in the fourth place means:\n If you are sincere, blood vanishes and fear gives way.\n No blame.",
    "line-5" : "Nine in the fifth place means:\n If you are sincere and loyally attached,\n You are rich in your neighbor.",
    "line-6" : "Nine at the top means:\n The rain comes, there is rest.\n This is due to the lasting effect of character.\n Perseverance brings the woman into danger.\n The moon is nearly full.\n If the superior man persists,\n Misfortune comes.",
  },
  {
    "number" : "10",
    "name-interpretation" : "Treading [conduct]",
    "judgment" : "TREADING. Treading upon the tail of the tiger.\n It does not bite the man. Success.",
    "line-1" : "Nine at the beginning means:\n Simple conduct. Progress without blame.",
    "line-2" : "Nine in the second place means:\n Treading a smooth, level course.\n The perseverance of a dark man\n Brings good fortune.",
    "line-3" : "Six in the third place means:\n A one-eyed man is able to see,\n A lame man is able to tread.\n He treads on the tail of the tiger.\n The tiger bites the man.\n Misfortune.\n Thus does a warrior act on behalf of his great prince.",
    "line-4" : "Nine in the fourth place means:\n He treads on the tail of the tiger.\n Caution and circumspection\n Lead ultimately to good fortune.",
    "line-5" : "Nine in the fifth place means:\n Resolute conduct.\n Perseverance with awareness of danger.",
    "line-6" : "Nine at the top means:\n Look to your conduct and weigh the favorable signs.\n When everything is fulfilled, supreme good fortune comes.",
  },
  {
    "number" : "11",
    "name-interpretation" : "Peace",
    "judgment" : "PEACE. The small departs,\n The great approaches.\n Good fortune. Success.",
    "line-1" : "Nine at the beginning means:\n When ribbon grass is pulled up, the sod comes with it.\n Each according to his kind.\n Undertakings bring good fortune.",
    "line-2" : "Nine in the second place means:\n Bearing with the uncultured in gentleness,\n Fording the river with resolution,\n Not neglecting what is distant,\n Not regarding one's companions:\n Thus one may manage to walk in the middle.",
    "line-3" : "Nine in the third place means:\n No plain not followed by a slope.\n No going not followed by a return.\n He who remains persevering in danger\n Is without blame.\n Do not complain about this truth;\n Enjoy the good fortune you still possess.",
    "line-4" : "Six in the fourth place means:\n He flutters down, not boasting of his wealth,\n Together with his neighbor,\n Guileless and sincere.",
    "line-5" : "Six in the fifth place means:\n The sovereign I\n Gives his daughter in marriage.\n And supreme good fortune.",
    "line-6" : "Six at the top means:\n The wall falls back into the moat.\n Use no army now.\n Make your commands known within your own town.\n Perseverance brings humiliation.",
  },
  {
    "number" : "12",
    "name-interpretation" : "Standstill [Stagnation]",
    "judgment" : "STANDSTILL. Evil people do not further\n The perseverance of the superior man.\n The great departs; the small approaches.",
    "line-1" : "Six at the beginning means:\n When ribbon grass is pulled up, the sod comes with it.\n Each according to his kind.\n Perseverance brings good fortune and success.",
    "line-2" : "Six in the second place means:\n They bear and endure;\n This means good fortune for inferior people.\n The standstill serves to help the great man to attain success.",
    "line-3" : "Six in the third place means:\n They bear shame.",
    "line-4" : "Nine in the fourth place means:\n He who acts at the command of the highest\n Remains without blame.\n Those of like mind partake of the blessing.",
    "line-5" : "Nine in the fifth place means:\n Standstill is giving way.\n Good fortune for the great man.\n &quot;What if it should fail, what if it should fail?&quot;\n In this way he ties it to a cluster of mulberry shoots.",
    "line-6" : "Nine at the top means:\n The standstill comes to an end.\n First standstill, then good fortune.",
  },
  {
    "number" : "13",
    "name-interpretation" : "Fellowship with Men",
    "judgment" : "FELLOWSHIP WITH MEN in the open.\n Success.\n It furthers one to cross the great water.\n The perseverance of the superior man furthers.",
    "line-1" : "Nine at the beginning means:\n Fellowship with men at the gate.\n No blame.",
    "line-2" : "Six in the second place means:\n Fellowship with men in the clan.\n Humiliation.",
    "line-3" : "Nine in the third place means:\n He hides weapons in the thicket;\n He climbs the high hill in front of it.\n For three years he does not rise up.",
    "line-4" : "Nine in the fourth place means:\n He climbs up on his wall; he cannot attack.\n Good fortune.",
    "line-5" : "Nine in the fifth place means:\n Men bound in fellowship first weep and lament,\n But afterward they laugh.\n After great struggles they succeed in meeting.",
    "line-6" : "Nine at the top means:\n Fellowship with men in the meadow.\n No remorse.",
  },
  {
    "number" : "14",
    "name-interpretation" : "Possession in Great Measure",
    "judgment" : "POSSESSION IN GREAT MEASURE.\n Supreme success.",
    "line-1" : "Nine at the beginning means:\n No relationship with what is harmful;\n There is no blame in this.\n If one remains conscious of difficulty,\n One remains without blame.",
    "line-2" : "Nine in the second place means:\n A big wagon for loading.\n One may undertake something.\n No blame.",
    "line-3" : "Nine in the third place means:\n A prince offers it to the Son of Heaven.\n A petty man cannot do this.",
    "line-4" : "Nine in the fourth place means:\n He makes a difference\n Between himself and his neighbor.\n No blame.",
    "line-5" : "Six in the fifth place means:\n He whose truth is accessible, yet dignified,\n Has good fortune.",
    "line-6" : "Nine at the top means:\n He is blessed by heaven.\n Good fortune.\n Nothing that does not further.",
  },
  {
    "number" : "15",
    "name-interpretation" : "Modesty",
    "judgment" : "MODESTY creates success.\n The superior man carries things through.",
    "line-1" : "Six at the beginning means:\n A superior man modest about his modesty\n May cross the great water.\n Good fortune.",
    "line-2" : "Six in the second place means:\n Modesty that comes to expression. Perseverance brings good fortune.",
    "line-3" : "Nine in the third place means:\n A superior man of modesty and merit\n Carries things to conclusion.\n Good fortune.",
    "line-4" : "Six in the fourth place means:\n Nothing that would not further modesty\n In movement.",
    "line-5" : "Six in the fifth place means:\n No boasting of wealth before one's neighbor.\n It is favorable to attack with force.\n Nothing that would not further.",
    "line-6" : "Six at the top means:\n Modesty that comes to expression.\n It is favorable to set armies marching\n To chastise one's own city and one's country.",
  },
  {
    "number" : "16",
    "name-interpretation" : "Enthusiasm",
    "judgment" : "ENTHUSIASM. It furthers one to install helpers\n And to set armies marching.",
    "line-1" : "Six at the beginning means:\n Enthusiasm that expresses itself\n Brings misfortune.",
    "line-2" : "Six in the second place means:\n Firm as a rock. Not a whole day.\n Perseverance brings good fortune.",
    "line-3" : "Six in the third place means:\n Enthusiasm that looks upward creates remorse.\n Hesitation brings remorse.",
    "line-4" : "Nine in the fourth place means:\n The source of enthusiasm.\n He achieves great things.\n Doubt not.\n You gather friends around you\n As a hair clasp gathers the hair.",
    "line-5" : "Six in the fifth place means:\n Persistently ill, and still does not die.",
    "line-6" : "Six at the top means:\n Deluded enthusiasm.\n But if after completion one changes,\n There is no blame.",
  },
  {
    "number" : "17",
    "name-interpretation" : "Following",
    "judgment" : "FOLLOWING has supreme success.\n Perseverance furthers. No blame.",
    "line-1" : "Nine at the beginning means:\n The standard is changing.\n Perseverance brings good fortune.\n To go out of the door in company\n Produces deeds.",
    "line-2" : "Six in the second place means:\n If one clings to the little boy,\n One loses the strong man.",
    "line-3" : "Six in the third place means:\n If one clings to the strong man,\n One loses the little boy.\n Through following one finds what one seeks.\n It furthers one to remain persevering.",
    "line-4" : "Nine in the fourth place means:\n Following creates success.\n Perseverance brings misfortune.\n To go one's way with sincerity brings clarity.\n How could there be blame in this?",
    "line-5" : "Nine in the fifth place means:\n Sincere in the good. Good fortune.",
    "line-6" : "Six at the top means:\n He meets with firm allegiance\n And is still further bound.\n The king introduces him\n To the Western Mountain.",
  },
  {
    "number" : "18",
    "name-interpretation" : "Work on what has been spoiled [ Decay ]",
    "judgment" : "WORK ON WHAT HAS BEEN SPOILED\n Has supreme success.\n It furthers one to cross the great water.\n Before the starting point, three days.\n After the starting point, three days.",
    "line-1" : "Six at the beginning means:\n Setting right what has been spoiled by the father.\n If there is a son,\n No blame rests upon the departed father.\n Danger. In the end good fortune.",
    "line-2" : "Nine in the second place means:\n Setting right what has been spoiled by the mother.\n One must not be too persevering.",
    "line-3" : "Nine in the third place means:\n Setting right what has been spoiled by the father.\n There will be a little remorse. No great blame.",
    "line-4" : "Six in the fourth place means:\n Tolerating what has been spoiled by the father.\n In continuing one sees humiliation.",
    "line-5" : "Six in the fifth place means:\n Setting right what has been spoiled by the father.\n One meets with praise.",
    "line-6" : "Nine at the top means:\n He does not serve kings and princes,\n Sets himself higher goals.",
  },
  {
    "number" : "19",
    "name-interpretation" : "Approach",
    "judgment" : "APPROACH has supreme success.\n Perseverance furthers.\n When the eighth month comes,\n There will be misfortune.",
    "line-1" : "Nine at the beginning means:\n Joint approach.\n Perseverance brings good fortune.",
    "line-2" : "Nine in the second place means:\n Joint approach.\n Good fortune.\n Everything furthers.",
    "line-3" : "Six in the third place means:\n Comfortable approach.\n Nothing that would further.\n If one is induced to grieve over it,\n One becomes free of blame.",
    "line-4" : "Six in the fourth place means:\n Complete approach.\n No blame.",
    "line-5" : "Six in the fifth place means:\n Wise approach.\n This is right for a great prince.\n Good fortune.",
    "line-6" : "Six at the top means:\n Great hearted approach.\n Good-hearted approach.\n Good fortune. No blame.",
  },
  {
    "number" : "20",
    "name-interpretation" : "Contemplation (View)",
    "judgment" : "CONTEMPLATION. The ablution has been made,\n But not yet the offering.\n Full of trust they look up to him.",
    "line-1" : "Six at the beginning means:\n Boy like contemplation.\n For an inferior man, no blame.\n For a superior man, humiliation.",
    "line-2" : "Six in the second place means:\n Contemplation through the crack of the door.\n Furthering for the perseverance of a woman.",
    "line-3" : "Six in the third place means:\n Contemplation of my life\n Decides the choice\n Between advance and retreat.",
    "line-4" : "Six in the fourth place means:\n Contemplation of the light of the kingdom.\n It furthers one to exert influence as the guest of a king.",
    "line-5" : "Nine in the fifth place means:\n Contemplation of my life.\n The superior man is without blame.",
    "line-6" : "Nine at the top means:\n Contemplation of his life.\n The superior man is without blame.",
  },
  {
    "number" : "21",
    "name-interpretation" : "Biting Through",
    "judgment" : "BITING THROUGH has success.\n It is favorable to let justice be administered.",
    "line-1" : "Nine at the beginning means:\n His feet are fastened in the stocks,\n So that his toes disappear.\n No blame.",
    "line-2" : "Six in the second place means:\n Bites through tender meat,\n So that his nose disappears.\n No blame.",
    "line-3" : "Six in the third place means:\n Bites on old dried meat\n And strikes on something poisonous.\n Slight humiliation. No blame.",
    "line-4" : "Nine in the fourth place means:\n Bites on dried gristly meat.\n Receives metal arrows.\n It furthers one to be mindful of difficulties\n And to be persevering.\n Good fortune.",
    "line-5" : "Six in the fifth place means:\n Bites on dried lean meat.\n Receives yellow gold.\n Perseveringly aware of danger.\n No blame.",
    "line-6" : "Nine at the top means:\n His neck is fastened in the wooden cangue,\n So that his ears disappear.\n Misfortune.",
  },
  {
    "number" : "22",
    "name-interpretation" : "Grace",
    "judgment" : "GRACE has success.\n In small matters\n It is favorable to undertake something.",
    "line-1" : "Nine at the beginning means:\n He lends grace to his toes, leaves the carriage, and walks.",
    "line-2" : "Six in the second place means:\n Lends grace to the beard on his chin.",
    "line-3" : "Nine in the third place means:\n Graceful and moist.\n Constant perseverance brings good fortune.",
    "line-4" : "Six in the fourth place means:\n Grace or simplicity?\n A white horse comes as if on wings.\n He is not a robber,\n He will woo at the right time.",
    "line-5" : "Six in the fifth place means:\n Grace in the hills and gardens.\n The roll of silk is meager and small.\n Humiliation, but in the end good fortune.",
    "line-6" : "Nine at the top means:\n Simple grace. No blame.",
  },
  {
    "number" : "23",
    "name-interpretation" : "Splitting Apart",
    "judgment" : "SPLITTING APART. IT does not further one\n To go anywhere.",
    "line-1" : "Six at the beginning means:\n The leg of the bed is split.\n Those who persevere are destroyed.\n Misfortune.",
    "line-2" : "Six in the second place means:\n The bed is split at the edge.\n Those who persevere are destroyed.\n Misfortune.",
    "line-3" : "Six in the third place means:\n He splits with them. No blame.",
    "line-4" : "Six in the fourth place means:\n The bed is split up to the skin.\n Misfortune.",
    "line-5" : "Six in the fifth place means:\n A shoal of fishes. Favor comes through the court ladies.\n Everything acts to further.",
    "line-6" : "Nine at the top means:\n There is a large fruit still uneaten.\n The superior man receives a carriage.\n The house of the inferior man is split apart.",
  },
  {
    "number" : "24",
    "name-interpretation" : "Return (The Turning Point)",
    "judgment" : "RETURN. Success.\n Going out and coming in without error.\n Friends come without blame.\n To and fro goes the way.\n On the seventh day comes return.\n It furthers one to have somewhere to go.",
    "line-1" : "Nine at the beginning means:\n Return from a short distance.\n No need for remorse.\n Great good fortune.",
    "line-2" : "Six in the second place means:\n Quiet return. Good fortune.",
    "line-3" : "Six in the third place means:\n Repeated return. Danger. No blame.",
    "line-4" : "Six in the fourth place means:\n Walking in the midst of others,\n One returns alone.",
    "line-5" : "Six in the fifth place means:\n Noblehearted return. No remorse.",
    "line-6" : "Six at the top means:\n Missing the return. Misfortune.\n Misfortune from within and without.\n If armies are set marching in this way,\n One will in the end suffer a great defeat,\n Disastrous for the ruler of the country.\n For ten years\n It will not be possible to attack again.",
  },
  {
    "number" : "25",
    "name-interpretation" : "Innocence (The Unexpected)",
    "judgment" : "INNOCENCE. Supreme success.\n Perseverance furthers.\n If someone is not as he should be,\n He has misfortune,\n And it does not further him\n To undertake anything.",
    "line-1" : "Nine at the beginning means:\n Innocent behavior brings good fortune.",
    "line-2" : "Six in the second place means:\n If one does not count on the harvest while plowing,\n Nor on the use of the ground while clearing it,\n It furthers one to undertake something.",
    "line-3" : "Six in the third place means:\n Undeserved misfortune.\n The cow that was tethered by someone\n Is the wanderer's gain, the citizen's loss.",
    "line-4" : "Nine in the fourth place means:\n He who can be persevering\n Remains without blame.",
    "line-5" : "Nine in the fifth place means:\n Use no medicine in an illness\n Incurred through no fault of your own.\n It will pass of itself.",
    "line-6" : "Nine at the top means:\n Innocent action brings misfortune.\n Nothing furthers.",
  },
  {
    "number" : "26",
    "name-interpretation" : "The Taming Power of the Great",
    "judgment" : "THE TAMING POWER OF THE GREAT.\n Perseverance furthers.\n Not eating at home brings good fortune.\n It furthers one to cross the great water.",
    "line-1" : "Nine at the beginning means:\n Danger is at hand. It furthers one to desist.",
    "line-2" : "Nine in the second place means:\n The axletrees are taken from the wagon.",
    "line-3" : "Nine in the third place means.\n A good horse that follows others.\n Awareness of danger,\n With perseverance, furthers.\n Practice chariot driving and armed defense daily.\n It furthers one to have somewhere to go.",
    "line-4" : "Six in the fourth place means:\n The headboard of a young bull.\n Great good fortune.",
    "line-5" : "Six in the fifth place means:\n The tusk of a gelded boar.\n Good fortune.",
    "line-6" : "Nine at the top means:\n One attains the way of heaven.\n Success.",
  },
  {
    "number" : "27",
    "name-interpretation" : "Corners of the Mouth (Providing Nourishment)",
    "judgment" : "THE CORNERS OF THE MOUTH.\n Perseverance brings good fortune.\n Pay heed to the providing of nourishment\n And to what a man seeks\n To fill his own mouth with.",
    "line-1" : "Nine at the beginning means:\n You let your magic tortoise go,\n And look at me with the corners of your mouth drooping.\n Misfortune.",
    "line-2" : "Six in the second place means:\n Turning to the summit for nourishment,\n Deviating from the path\n To seek nourishment from the hill.\n Continuing to do this brings misfortune.",
    "line-3" : "Six in the third place means:\n Turning away from nourishment.\n Perseverance brings misfortune.\n Do not act thus for ten years.\n Nothing serves to further.",
    "line-4" : "Six in the fourth place means:\n Turning to the summit\n For provision of nourishment\n Brings good fortune.\n Spying about with sharp eyes\n Like a tiger with insatiable craving.\n No blame.",
    "line-5" : "Six in the fifth place means:\n Turning away from the path.\n To remain persevering brings good fortune.\n One should not cross the great water.",
    "line-6" : "Nine at the top means:\n The source of nourishment.\n Awareness of danger brings good fortune.\n It furthers one to cross the great water.",
  },
  {
    "number" : "28",
    "name-interpretation" : "Preponderance of the Great",
    "judgment" : "PREPONDERANCE OF THE GREAT.\n The ridgepole sags to the breaking point.\n It furthers one to have somewhere to go.\n Success.",
    "line-1" : "Six at the beginning means:\n To spread white rushes underneath.\n No blame.",
    "line-2" : "Nine in the second place means:\n A dry poplar sprouts at the root.\n An older man takes a young wife.\n Everything furthers.",
    "line-3" : "Nine in the third place means:\n The ridgepole sags to the breaking point.\n Misfortune.",
    "line-4" : "Nine in the fourth place means:\n The ridgepole is braced. Good fortune.\n If there are ulterior motives, it is humiliating.",
    "line-5" : "Nine in the fifth place means:\n A withered poplar puts forth flowers.\n An older woman takes a husband.\n No blame. No praise.",
    "line-6" : "Six at the top means:\n One must go through the water.\n It goes over one's head.\n Misfortune. No blame.",
  },
  {
    "number" : "29",
    "name-interpretation" : "The Abysmal (Water)",
    "judgment" : "The Abysmal repeated.\n If you are sincere, you have success in your heart,\n And whatever you do succeeds.",
    "line-1" : "Six at the beginning means:\n Repetition of the Abysmal.\n In the abyss one falls into a pit.\n Misfortune.",
    "line-2" : "Nine in the second place means:\n The abyss is dangerous.\n One should strive to attain small things only.",
    "line-3" : "Six in the third place means:\n Forward and backward, abyss on abyss.\n In danger like this, pause at first and wait,\n Otherwise you will fall into a pit in the abyss.\n Do not act this way.",
    "line-4" : "Six in the fourth place means:\n A jug of wine, a bowl of rice with it;\n Earthen vessels\n Simply handed in through the Window.\n There is certainly no blame in this.",
    "line-5" : "Nine in the fifth place means:\n The abyss is not filled to overflowing,\n It is filled only to the rim.\n No blame.",
    "line-6" : "Six at the top means:\n Bound with cords and ropes,\n Shut in between thorn-hedged prison walls:\n For three years one does not find the way.\n Misfortune.",
  },
  {
    "number" : "30",
    "name-interpretation" : "The Clinging, Fire",
    "judgment" : "THE CLINGING. Perseverance furthers.\n It brings success.\n Care of the cow brings good fortune.",
    "line-1" : "Nine at the beginning means:\n The footprints run crisscross.\n If one is seriously intent, no blame.",
    "line-2" : "Six in the second place means:\n Yellow light. Supreme good fortune.",
    "line-3" : "Nine in the third place means:\n In the light of the setting sun,\n Men either beat the pot and sing\n Or loudly bewail the approach of old age.\n Misfortune.",
    "line-4" : "Nine in the fourth place means:\n Its coming is sudden;\n It flames up, dies down, is thrown away.",
    "line-5" : "Six in the fifth place means:\n Tears in floods, sighing and lamenting.\n Good fortune.",
    "line-6" : "Nine at the top means:\n The king used him to march forth and chastise.\n Then it is best to kill the leaders\n And take captive the followers. No blame.",
  },
  {
    "number" : "31",
    "name-interpretation" : "Influence (Wooing)",
    "judgment" : "INFLUENCE. Success.\n Perseverance furthers.\n To take a maiden to wife brings good fortune.",
    "line-1" : "Six at the beginning means:\n The influence shows itself in the big toe.",
    "line-2" : "Six in the second place means:\n The influence shows itself in the calves of the legs.\n Misfortune.\n Tarrying brings good fortune.",
    "line-3" : "Nine in the third place means:\n The influence shows itself in the thighs.\n Holds to that which follows it.\n To continue is humiliating.",
    "line-4" : "Nine in the fourth place means:\n Perseverance brings good fortune.\n Remorse disappears.\n If a man is agitated in mind,\n And his thoughts go hither and thither,\n Only those friends\n On whom he fixes his conscious thoughts\n Will follow.",
    "line-5" : "Nine in the fifth place means:\n The influence shows itself in the back of the neck.\n No remorse.",
    "line-6" : "Six at the top means:\n The influence shows itself in the jaws, cheeks, and tongue.",
  },
  {
    "number" : "32",
    "name-interpretation" : "Duration",
    "judgment" : "DURATION. Success. No blame.\n Perseverance furthers.\n It furthers one to have somewhere to go.",
    "line-1" : "Six at the beginning means:\n Seeking duration too hastily brings misfortune persistently.\n Nothing that would further.",
    "line-2" : "Nine in the second place means:\n Remorse disappears.",
    "line-3" : "Nine in the third place means:\n He who does not give duration to his character\n Meets with disgrace.\n Persistent humiliation.",
    "line-4" : "Nine in the fourth place means:\n No game in the field.",
    "line-5" : "Six in the fifth place means:\n Giving duration to one's character through perseverance.\n This is good fortune for a woman, misfortune for a man.",
    "line-6" : "Six at the top means:\n Restlessness as an enduring condition brings misfortune.",
  },
  {
    "number" : "33",
    "name-interpretation" : "Retreat",
    "judgment" : "RETREAT. Success.\n In what is small, perseverance furthers.",
    "line-1" : "Six at the beginning means:\n At the tail in retreat. This is dangerous.\n One must not wish to undertake anything.",
    "line-2" : "Six in the second place means:\n he holds him fast with yellow oxhide.\n No one can tear him loose.",
    "line-3" : "Nine in the third place means:\n A halted retreat\n Is nerve-wracking and dangerous.\n To retain people as men- and maidservants\n Brings good fortune.",
    "line-4" : "Nine in the fourth place means:\n Voluntary retreat brings good fortune to the superior man\n And downfall to the inferior man.",
    "line-5" : "Nine in the fifth place means:\n Friendly retreat. Perseverance brings good fortune.",
    "line-6" : "Nine at the top means:\n Cheerful retreat. Everything serves to further.",
  },
  {
    "number" : "34",
    "name-interpretation" : "The Power of the Great",
    "judgment" : "THE POWER OF THE GREAT. Perseverance furthers.",
    "line-1" : "Nine at the beginning means:\n Power in the toes.\n Continuing brings misfortune.\n This is certainly true.",
    "line-2" : "Nine in the second place means:\n Perseverance brings good fortune.",
    "line-3" : "Nine in the third place means:\n The inferior man works through power.\n The superior man does not act thus.\n To continue is dangerous.\n A goat butts against a hedge\n And gets its horns entangled.",
    "line-4" : "Nine in the fourth place means:\n Perseverance brings good fortune.\n Remorse disappears.\n The hedge opens; there is no entanglement.\n Power depends upon the axle of a big cart.",
    "line-5" : "Six in the fifth place means:\n Loses the goat with ease.\n No remorse.",
    "line-6" : "Six at the top means:\n A goat butts against a hedge.\n It cannot go backward, it cannot go forward.\n Nothing serves to further.\n If one notes the difficulty, this brings good fortune.",
  },
  {
    "number" : "35",
    "name-interpretation" : "Progress",
    "judgment" : "PROGRESS. The powerful prince\n Is honored with horses in large numbers.\n In a single day he is granted audience three times.",
    "line-1" : "Six at the beginning means:\n Progressing, but turned back.\n Perseverance brings good fortune.\n If one meets with no confidence, one should remain calm.\n No mistake.",
    "line-2" : "Six in the second place means:\n Progressing, but in sorrow.\n Perseverance brings good fortune.\n Then one obtains great happiness from one's ancestress.",
    "line-3" : "Six in the third place means:\n All are in accord. Remorse disappears.",
    "line-4" : "Nine in the fourth place means:\n Progress like a hamster.\n Perseverance brings danger.",
    "line-5" : "Six in the fifth place means:\n Remorse disappears.\n Take not gain and loss to heart.\n Undertakings bring good fortune.\n Everything serves to further.",
    "line-6" : "Nine at the top means:\n Making progress with the horns is permissible\n Only for the purpose of punishing one's own city.\n To be conscious of danger brings good fortune.\n No blame.\n Perseverance brings humiliation.",
  },
  {
    "number" : "36",
    "name-interpretation" : "Darkening of the light",
    "judgment" : "DARKENING OF THE LIGHT. In adversity\n It furthers one to be persevering.",
    "line-1" : "Nine at the beginning means:\n Darkening of the light during flight.\n He lowers his wings.\n The superior man does not eat for three days\n On his wanderings.\n But he has somewhere to go.\n The host has occasion to gossip about him.",
    "line-2" : "Six in the second place means:\n Darkening of the light injures him in the left thigh.\n He gives aid with the strength of a horse.\n Good fortune.",
    "line-3" : "Nine in the third place means:\n Darkening of the light during the hunt in the south.\n Their great leader is captured.\n One must not expect perseverance too soon.",
    "line-4" : "Six in the fourth place means:\n He penetrates the left side of the belly.\n One gets at the very heart of the darkening of the light.",
    "line-5" : "Six in the fifth place means:\n Darkening of the light as with Prince Chi.\n Perseverance furthers.",
    "line-6" : "Six at the top means:\n Not light but darkness.\n First he climbed up to heaven,\n Then plunged into the depths of the earth.",
  },
  {
    "number" : "37",
    "name-interpretation" : "The Family [The Clan]",
    "judgment" : "THE FAMILY. The perseverance of the woman furthers.",
    "line-1" : "Nine at the beginning means:\n Firm seclusion within the family.\n Remorse disappears.",
    "line-2" : "Six in the second place means:\n She should not follow her whims.\n She must attend within to the food.\n Perseverance brings good fortune.",
    "line-3" : "Nine in the third place means:\n When tempers flare up in the family,\n Too great severity brings remorse.\n Good fortune nonetheless.\n When woman and child dally and laugh\n It leads in the end to humiliation.",
    "line-4" : "Six in the fourth place means:\n She is the treasure of the house.\n Great good fortune.",
    "line-5" : "Nine in the fifth place means:\n As a king he approaches his family.\n Fear not.\n Good fortune.",
    "line-6" : "Nine at the top means:\n His work commands respect.\n In the end good fortune comes.",
  },
  {
    "number" : "38",
    "name-interpretation" : "Opposition",
    "judgment" : "OPPOSITION. In small matters, good fortune.",
    "line-1" : "Nine at the beginning means:\n Remorse disappears.\n If you lose your horse, do not run after it;\n It will come back of its own accord.\n When you see evil people,\n Guard yourself against mistakes.",
    "line-2" : "Nine in the second place means:\n One meets his lord in a narrow street.\n No blame.",
    "line-3" : "Six in the third place means:\n One sees the wagon dragged back,\n The oxen halted,\n A man's hair and nose cut off.\n Not a good beginning, but a good end.",
    "line-4" : "Nine in the fourth place means:\n Isolated through opposition,\n One meets a like-minded man\n With whom one can associate in good faith.\n Despite the danger, no blame.",
    "line-5" : "Six in the fifth place means:\n Remorse disappears.\n The companion bites his way through the wrappings.\n If one goes to him,\n How could it be a mistake?",
    "line-6" : "Nine at the top means:\n Isolated through opposition,\n One sees one's companion as a pig covered with dirt,\n As a wagon full of devils.\n First one draws a bow against him,\n then one lays the bow aside.\n He is not a robber; he will woo at the right time.\n As one goes, rain falls; then good fortune comes.",
  },
  {
    "number" : "39",
    "name-interpretation" : "Obstruction",
    "judgment" : "OBSTRUCTION. The southwest furthers.\n The northeast does not further.\n It furthers one to see the great man.\n Perseverance brings good fortune.",
    "line-1" : "Six at the beginning means:\n Going leads to obstructions,\n Coming meets with praise.",
    "line-2" : "Six in the second place means:\n The King's servant is beset by obstruction upon obstruction,\n But it is not his own fault.",
    "line-3" : "Nine in the third place means:\n Going leads to obstructions;\n Hence he comes back.",
    "line-4" : "Six in the fourth place means:\n Going leads to obstructions,\n Coming leads to union.",
    "line-5" : "Nine in the fifth place means:\n In the midst of the greatest obstructions,\n Friends come.",
    "line-6" : "Six at the top means:\n Going leads to obstructions,\n Coming leads to great good fortune.\n It furthers one to see the great man.",
  },
  {
    "number" : "40",
    "name-interpretation" : "Deliverance",
    "judgment" : "DELIVERANCE. The southwest furthers.\n If there is no longer anything where one has to go,\n Return brings good fortune.\n If there is still something where one has to go,\n Hastening brings good fortune.",
    "line-1" : "Six at the beginning means:\n Without blame.",
    "line-2" : "Nine in the second place means:\n One kills three foxes in the field\n And receives a yellow arrow.\n Perseverance brings good fortune.",
    "line-3" : "Six in the third place means:\n If a man carries a burden on his back\n And nonetheless rides in a carriage,\n He thereby encourages robbers to draw near.\n Perseverance leads to humiliation.",
    "line-4" : "Nine in the fourth place means:\n Deliver yourself from your great toe.\n Then the companion comes,\n And him you can trust.",
    "line-5" : "Six in the fifth place means:\n If only the superior man can deliver himself,\n It brings good fortune.\n Thus he proves to inferior men that he is in earnest.",
    "line-6" : "Six at the top means:\n The prince shoots at a hawk on a high wall.\n He kills it. Everything serves to further.",
  },
  {
    "number" : "41",
    "name-interpretation" : "Decrease",
    "judgment" : "DECREASE combined with sincerity\n Brings about supreme good fortune\n Without blame.\n One may be persevering in this.\n It furthers one to undertake something.\n How is this to be carried out?\n One may use two small bowls for the sacrifice.",
    "line-1" : "Nine at the beginning means:\n Going quickly when one's tasks are finished\n Is without blame.\n But one must reflect on how much one may decrease others.",
    "line-2" : "Nine in the second place means:\n Perseverance furthers.\n To undertake something brings misfortune.\n Without decreasing oneself,\n One is able to bring increase to others.",
    "line-3" : "Six in the third place means:\n When three people journey together,\n Their number increases by one.\n When one man journeys alone,\n He finds a companion.",
    "line-4" : "Six in the fourth place means:\n If a man deceases his faults,\n It makes the other hasten to come and rejoice.\n No blame.",
    "line-5" : "Six in the fifth place means:\n Someone does indeed increase him.\n Ten pairs of tortoises cannot oppose it.\n Supreme good fortune.",
    "line-6" : "Nine at the top means:\n If one is increased without depriving other,\n There is no blame.\n Perseverance brings good fortune.\n It furthers one to undertake something.\n One obtains servants\n But no longer has a separate home.",
  },
  {
    "number" : "42",
    "name-interpretation" : "Increase",
    "judgment" : "INCREASE. It furthers one\n To undertake something.\n It furthers one to cross the great water.",
    "line-1" : "Nine at the beginning means:\n It furthers one to accomplish great deeds.\n Supreme good fortune. No blame.",
    "line-2" : "Six in the second place means:\n Someone does indeed increase him;\n Ten pairs of tortoises cannot oppose it.\n Constant perseverance brings good fortune.\n The king presents him before God.\n Good fortune.",
    "line-3" : "Six in the third place means:\n One is enriched through unfortunate events.\n No blame, if you are sincere\n And walk in the middle,\n And report with a seal to the prince.",
    "line-4" : "Six in the fourth place means:\n If you walk in the middle\n And report the prince,\n He will follow.\n It furthers one to be used\n In the removal of the capital.",
    "line-5" : "Nine in the fifth place means:\n If in truth you have a kind heart, ask not.\n Supreme good fortune.\n Truly, kindness will be recognized as your virtue.",
    "line-6" : "Nine at the top means:\n He brings increase to no one.\n Indeed, someone even strikes him.\n He does not keep his heart constantly steady.\n Misfortune.",
  },
  {
    "number" : "43",
    "name-interpretation" : "Break-through (Resoluteness)",
    "judgment" : "BREAK-THROUGH. One must resolutely make the matter known\n At the court of the king.\n It must be announced truthfully. Danger.\n It is necessary to notify one's own city.\n It does not further to resort to arms.\n It furthers one to undertake something.",
    "line-1" : "Nine at the beginning means:\n Mighty in the forward-striding toes.\n When one goes and is not equal to the task,\n One makes a mistake.",
    "line-2" : "Nine in the second place means:\n A cry of alarm. Arms at evening and at night.\n Fear nothing.",
    "line-3" : "Nine in the third place means:\n To be powerful in the cheekbones\n Brings misfortune.\n The superior man is firmly resolved.\n He walks alone and is caught in the rain.\n He is bespattered,\n And people murmur against him.\n No blame.",
    "line-4" : "Nine in the fourth place means:\n There is no skin on his thighs,\n And walking comes hard.\n If a man were to let himself be led like a sheep,\n Remorse would disappear.\n But if these words are heard\n They will not be believed.",
    "line-5" : "Nine in the fifth place means:\n In dealing with weeds,\n Firm resolution is necessary.\n Walking in the middle\n Remains free of blame.",
    "line-6" : "Six at the top means:\n No cry.\n In the end misfortune comes.",
  },
  {
    "number" : "44",
    "name-interpretation" : "Coming to Meet",
    "judgment" : "COMING TO MEET. The maiden is powerful.\n One should not marry such a maiden.",
    "line-1" : "Six at the beginning means:\n It must be checked with a brake of bronze.\n Perseverance brings good fortune.\n If one lets it take its course, one experiences misfortune.\n Even a lean pig has it in him to rage around.",
    "line-2" : "Nine in the second place means:\n There is a fish in the tank. No blame.\n Does not further guests.",
    "line-3" : "Nine in the third place means:\n There is no skin on his thighs,\n And walking comes hard.\n If one is mindful of the danger,\n No great mistake is made.",
    "line-4" : "Nine in the fourth place means:\n No fish in the tank.\n This leads to misfortune.",
    "line-5" : "Nine in the fifth place means:\n A melon covered with willow leaves.\n Hidden lines.\n Then it drops down to one from heaven.",
    "line-6" : "Nine at the top means:\n He comes to meet with his horns.\n Humiliation. No blame.",
  },
  {
    "number" : "45",
    "name-interpretation" : "Gathering Together [Massing]",
    "judgment" : "GATHERING TOGETHER. Success.\n The king approaches his temple.\n It furthers one to see the great man.\n This brings success. Perseverance furthers.\n To bring great offerings creates good fortune.\n It furthers one to undertake something.",
    "line-1" : "Six at the beginning means:\n If you are sincere, but not to the end,\n There will sometimes be confusion, sometimes gathering together.\n If you call out,\n Then after one grasp of the hand you can laugh again.\n Regret not. Going is without blame.",
    "line-2" : "Six in the second place means:\n Letting oneself be drawn\n Brings good fortune and remains blameless.\n If one is sincere,\n It furthers one to bring even a small offering.",
    "line-3" : "Six in the third place means:\n Gathering together amid sighs.\n Nothing that would further.\n Going is without blame.\n Slight humiliation.",
    "line-4" : "Nine in the fourth place means:\n Great good fortune. No blame.",
    "line-5" : "Nine in the fifth place means:\n If in gathering together one has position,\n This brings no blame.\n If there are some who are not yet sincerely in the work,\n Sublime and enduring perseverance is needed.\n Then remorse disappears.",
    "line-6" : "Six at the top means:\n Lamenting and sighing, floods of tears.\n No blame.",
  },
  {
    "number" : "46",
    "name-interpretation" : "Pushing Upward",
    "judgment" : "PUSHING UPWARD has supreme success.\n One must see the great man.\n Fear not.\n Departure toward the south\n Brings good fortune.",
    "line-1" : "Six at the beginning means:\n Pushing upward that meets with confidence\n Brings great good fortune.",
    "line-2" : "Nine in the second place means:\n If one is sincere,\n It furthers one to bring even a small offering.\n No blame.",
    "line-3" : "Nine in the third place means:\n One pushes upward into an empty city.",
    "line-4" : "Six in the fourth place means:\n The king offers him Mount Ch'i.\n Good fortune. No blame.",
    "line-5" : "Six in the fifth place means:\n Perseverance brings good fortune.\n One pushes upward by steps.",
    "line-6" : "Six at the top means:\n Pushing upward in darkness.\n It furthers one\n To be unremittingly persevering.",
  },
  {
    "number" : "47",
    "name-interpretation" : "Oppression (Exhaustion)",
    "judgment" : "OPPRESSION. Success. Perseverance.\n The great man brings about good fortune.\n No blame.\n When one has something to say,\n It is not believed.",
    "line-1" : "Six at the beginning means:\n One sits oppressed under a bare tree\n And strays into a gloomy valley.\n For three years one sees nothing.",
    "line-2" : "Nine in the second place means:\n One is oppressed while at meat and drink.\n The man with the scarlet knee bands is just coming.\n It furthers one to offer sacrifice.\n To set forth brings misfortune.\n No blame.",
    "line-3" : "Six in the third place means:\n A man permits himself to be oppressed by stone,\n And leans on thorns and thistles.\n He enters the house and does not see his wife.\n Misfortune.",
    "line-4" : "Nine in the fourth place means:\n He comes very quietly, oppressed in a golden carriage.\n Humiliation, but the end is reached.",
    "line-5" : "Nine in the fifth place means:\n His nose and feet are cut off.\n Oppression at the hands of the man with the purple knee bands.\n Joy comes softly.\n It furthers one to make offerings and libations.",
    "line-6" : "Six at the top means:\n He is oppressed by creeping vines.\n He moves uncertainly and says, &quot;Movement brings remorse.&quot;\n If one feels remorse over this and makes a start,\n Good fortune comes.",
  },
  {
    "number" : "48",
    "name-interpretation" : "The Well",
    "judgment" : "THE WELL. The town may be changed,\n But the well cannot be changed.\n It neither decreases nor increases.\n They come and go and draw from the well.\n If one gets down almost to the water\n And the rope does not go all the way,\n Or the jug breaks, it brings misfortune.",
    "line-1" : "Six at the beginning means:\n One does not drink the mud of the well.\n No animals come to an old well.",
    "line-2" : "Nine in the second place means:\n At the well hole one shoots fishes.\n The jug is broken and leaks.",
    "line-3" : "Nine in the third place means:\n The well is cleaned, but no one drinks from it.\n This is my heart's sorrow,\n For one might draw from it.\n If the king were clear-minded,\n Good fortune might be enjoyed in common.",
    "line-4" : "Six in the fourth place means:\n The well is being lined. No blame.",
    "line-5" : "Nine in the fifth place means:\n In the well there is a clear, cold spring\n From which one can drink.",
    "line-6" : "Six at the top means:\n One draws from the well\n Without hindrance.\n It is dependable.\n Supreme good fortune.",
  },
  {
    "number" : "49",
    "name-interpretation" : "Revolution (Molting)",
    "judgment" : "REVOLUTION. On your own day\n You are believed.\n Supreme success,\n Furthering through perseverance.\n Remorse disappears.",
    "line-1" : "Nine at the beginning means:\n Wrapped in the hide of a yellow cow.",
    "line-2" : "Six in the second place means:\n When one's own day comes, one may create revolution.\n Starting brings good fortune. No blame.",
    "line-3" : "Nine in the third place means:\n Starting brings misfortune.\n Perseverance brings danger.\n When talk of revolution has gone the rounds three times,\n One may commit himself,\n And men will believe him.",
    "line-4" : "Nine in the fourth place means:\n Remorse disappears. Men believe him.\n Changing the form of government brings good fortune.",
    "line-5" : "Nine in the fifth place means:\n The great man changes like a tiger.\n Even before he questions the oracle\n He is believed.",
    "line-6" : "Six at the top means:\n The superior man changes like a panther.\n The inferior man molts in the face.\n Starting brings misfortune.\n To remain persevering brings good fortune.",
  },
  {
    "number" : "50",
    "name-interpretation" : "The Caldron",
    "judgment" : "THE CALDRON. Supreme good fortune.\n Success.",
    "line-1" : "Six at the beginning means:\n A ting with legs upturned.\n Furthers removal of stagnating stuff.\n One takes a concubine for the sake of her son.\n No blame.",
    "line-2" : "Nine in the second place means:\n There is food in the ting.\n My comrades are envious,\n But they cannot harm me.\n Good fortune.",
    "line-3" : "Nine in the third place means:\n The handle of the ting is altered.\n One is impeded in his way of life.\n The fat of the pheasant is not eaten.\n Once rain falls, remorse is spent.\n Good fortune comes in the end.",
    "line-4" : "Nine in the fourth place means:\n The legs of the ting are broken.\n The prince's meal is spilled\n And his person is soiled.\n Misfortune.",
    "line-5" : "Six in the fifth place means:\n The ting has yellow handles, golden carrying rings.\n Perseverance furthers.",
    "line-6" : "Nine at the top means:\n The ting has rings of jade.\n Great good fortune.\n Nothing that would not act to further.",
  },
  {
    "number" : "51",
    "name-interpretation" : "The Arousing (Shock, Thunder)",
    "judgment" : "SHOCK brings success.\n Shock comes-oh, oh!\n Laughing words -ha, ha!\n The shock terrifies for a hundred miles,\n And he does not let fall the sacrificial spoon and chalice.",
    "line-1" : "Nine at the beginning means:\n Shock comes-oh, oh!\n Then follow laughing words-ha, ha!\n Good fortune.",
    "line-2" : "Six in the second place means:\n Shock comes bringing danger.\n A hundred thousand times\n You lose your treasures\n And must climb the nine hills.\n Do not go in pursuit of them.\n After seven days you will get them back again.",
    "line-3" : "Six in the third place means:\n Shock comes and makes one distraught.\n If shock spurs to action\n One remains free of misfortune.",
    "line-4" : "Nine in the fourth place means:\n Shock is mired.",
    "line-5" : "Six in the fifth place means:\n Shock goes hither and thither.\n Danger.\n However, nothing at all is lost.\n Yet there are things to be done.",
    "line-6" : "Six at the top means:\n Shock brings ruin and terrified gazing around.\n Going ahead brings misfortune.\n If it has not yet touched one's own body\n But has reached one's neighbor first,\n There is no blame.\n One's comrades have something to talk about.",
  },
  {
    "number" : "52",
    "name-interpretation" : "Keeping Still, Mountain",
    "judgment" : "KEEPING STILL. Keeping his back still\n So that he no longer feels his body.\n He goes into his courtyard\n And does not see his people.\n No blame.",
    "line-1" : "Six at the beginning means:\n Keeping his toes still.\n No blame.\n Continued perseverance furthers.",
    "line-2" : "Six in the second place means:\n Keeping his calves still.\n He cannot rescue him whom he follows.\n His heart is not glad.",
    "line-3" : "Nine in the third place means:\n Keeping his hips still.\n Making his sacrum stiff.\n Dangerous. The heart suffocates.",
    "line-4" : "Six in the fourth place means:\n Keeping his trunk still.\n No blame.",
    "line-5" : "Six in the fifth place means:\n Keeping his jaws still.\n The words have order.\n Remorse disappears.",
    "line-6" : "Nine at the top means:\n Noblehearted keeping still.\n Good fortune.",
  },
  {
    "number" : "53",
    "name-interpretation" : "Development (Gradual Progress)",
    "judgment" : "DEVELOPMENT. The maiden\n Is given in marriage.\n Good fortune.\n Perseverance furthers.",
    "line-1" : "Six at the beginning means:\n The wild goose gradually draws near the shore.\n The young son is in danger.\n There is talk. No blame.",
    "line-2" : "Six in the second place means:\n The wild goose gradually draws near the cliff.\n Eating and drinking in peace and concord.\n Good fortune.",
    "line-3" : "Nine in the third place means:\n The wild goose gradually draws near the plateau.\n The man goes forth and does not return.\n The woman carries a child but does not bring it forth.\n Misfortune.\n It furthers one to fight off robbers.",
    "line-4" : "Six in the fourth place means:\n The wild goose goes gradually draws near the tree.\n Perhaps it will find a flat branch. No blame.",
    "line-5" : "Nine in the fifth place means:\n The wild goose gradually draws near the summit.\n For three years the woman has no child.\n In the end nothing can hinder her.\n Good fortune.",
    "line-6" : "Nine at the top means:\n The wild goose gradually draws near the clouds heights.\n Its feathers can be used for the sacred dance.\n Good fortune.",
  },
  {
    "number" : "54",
    "name-interpretation" : "The Marrying Maiden",
    "judgment" : "THE MARRYING MAIDEN.\n Undertakings bring misfortune.\n Nothing that would further.",
    "line-1" : "Nine at the beginning means:\n The marrying maiden as a concubine.\n A lame man who is able to tread.\n Undertakings bring good fortune.",
    "line-2" : "Nine in the second place means:\n A one-eyed man who is able to see.\n The perseverance of a solitary man furthers.",
    "line-3" : "Six in the third place means:\n The marrying maiden as a slave.\n She marries as a concubine.",
    "line-4" : "Nine in the fourth place means:\n The marrying maiden draws out the allotted time.\n A late marriage comes in due course.",
    "line-5" : "Six in the fifth place means:\n The sovereign I gave his daughter in marriage.\n The embroidered garments of the princess\n Were not as gorgeous\n As those of the serving maid.\n The moon that is nearly full\n Brings good fortune.",
    "line-6" : "Six at the top means:\n The woman holds the basket, but there are no fruits in it.\n The man stabs the sheep, but no blood flows.\n Nothing that acts to further.",
  },
  {
    "number" : "55",
    "name-interpretation" : "Abundance [Fullness]",
    "judgment" : "ABUNDANCE has success.\n The king attains abundance.\n Be not sad.\n Be like the sun at midday.",
    "line-1" : "Nine at the beginning means:\n When a man meets his destined ruler,\n They can be together ten days,\n And it is not a mistake.\n Going meets with recognition.",
    "line-2" : "Six in the second place means:\n The curtain is of such fullness\n That the polestars can be seen at noon.\n Through going one meets with mistrust and hate.\n If one rouses him through truth,\n Good fortune comes.",
    "line-3" : "Nine in the third place means:\n The underbrush is of such abundance\n That the small stars can be seen at noon.\n He breaks his right arm . No blame.",
    "line-4" : "Nine in the fourth place means:\n The curtain is of such fullness\n That the polestars can be seen at noon.\n He meets his ruler, who is of like kind.\n Good fortune.",
    "line-5" : "Six in the fifth place means:\n Lines are coming,\n Blessing and fame draw near.\n Good fortune.",
    "line-6" : "Six at the top means:\n His house is in a state of abundance.\n He screens off his family.\n He peers through the gate\n And no longer perceives anyone.\n For three years he sees nothing.\n Misfortune.",
  },
  {
    "number" : "56",
    "name-interpretation" : "The Wanderer",
    "judgment" : "THE WANDERER. Success through smallness.\n Perseverance brings good fortune\n To the wanderer.",
    "line-1" : "Six at the beginning means:\n If the wanderer busies himself with trivial things,\n He draws down misfortune upon himself.",
    "line-2" : "Six in the second place means:\n The wanderer comes to an inn.\n He has his property with him.\n He wins the steadfastness of a young servant.",
    "line-3" : "Nine in the third place means:\n The wanderer's inn burns down.\n He loses the steadfastness of his young servant.\n Danger.",
    "line-4" : "Nine in the fourth place means:\n The wanderer rests in a shelter.\n He obtains his property and an ax.\n My heart is not glad.",
    "line-5" : "Six in the fifth place means:\n He shoots a pheasant.\n It drops with the first arrow.\n In the end this brings both praise and office.",
    "line-6" : "Nine at the top means:\n The bird's nest burns up.\n The wanderer laughs at first,\n Then must needs lament and weep.\n Through carelessness he loses his cow.\n Misfortune.",
  },
  {
    "number" : "57",
    "name-interpretation" : "The Gentle (The Penetrating, Wind)",
    "judgment" : "THE GENTLE. Success through what is small.\n It furthers one to have somewhere to go.\n It furthers one to see the great man.",
    "line-1" : "Six at the beginning means:\n In advancing and in retreating,\n The perseverance of a warrior furthers.",
    "line-2" : "Nine in the second place means:\n Penetration under the bed.\n Priests and magicians are used in great number.\n Good fortune. No blame.",
    "line-3" : "Nine in the third place means:\n Repeated penetration. Humiliation.",
    "line-4" : "Six in the fourth place means:\n Remorse vanishes.\n During the hunt\n Three kinds of game are caught.",
    "line-5" : "Nine in the fifth place means:\n Perseverance brings good fortune.\n Remorse vanishes.\n Nothing that does not further.\n No beginning, but an end.\n Before the change, three days.\n After the change, three days.\n Good fortune.",
    "line-6" : "Nine at the top means:\n Penetration under the bed.\n He loses his property and his ax.\n Perseverance brings misfortune.",
  },
  {
    "number" : "58",
    "name-interpretation" : "The Joyous, Lake",
    "judgment" : "THE JOYOUS. Success.\n Perseverance is favorable.",
    "line-1" : "Nine at the beginning means:\n Contented joyousness. Good fortune.",
    "line-2" : "Nine in the second place means:\n Sincere joyousness. Good fortune.\n Remorse disappears.",
    "line-3" : "Six in the third place means:\n Coming joyousness. Misfortune.",
    "line-4" : "Nine in the fourth place means:\n Joyousness that is weighed is not at peace.\n After ridding himself of mistakes a man has joy.",
    "line-5" : "Nine in the fifth place means:\n Sincerity toward disintegrating influences is dangerous.",
    "line-6" : "Six at the top means:\n Seductive joyousness.",
  },
  {
    "number" : "59",
    "name-interpretation" : "Dispersion [Dissolution]",
    "judgment" : "DISPERSION. Success.\n The king approaches his temple.\n It furthers one to cross the great water.\n Perseverance furthers.",
    "line-1" : "Six at the beginning means:\n He brings help with the strength of a horse.\n Good fortune.",
    "line-2" : "Nine in the second place means:\n At the dissolution\n He hurries to that which supports him.\n Remorse disappears.",
    "line-3" : "Six in the third place means:\n He dissolves his self. No remorse.",
    "line-4" : "Six in the fourth place means:\n He dissolves his bond with his group.\n Supreme good fortune.\n Dispersion leads in turn to accumulation.\n This is something that ordinary men do not think of.",
    "line-5" : "Nine in the fifth place means:\n His loud cries are as dissolving as sweat.\n Dissolution! A king abides without blame.",
    "line-6" : "Nine at the top means:\n He dissolves his blood.\n Departing, keeping at a distance, going out,\n Is without blame.",
  },
  {
    "number" : "60",
    "name-interpretation" : "Limitation",
    "judgment" : "LIMITATION. Success.\n Galling limitation must not be persevered in.",
    "line-1" : "Nine at the beginning means:\n Not going out of the door and the courtyard\n Is without blame.",
    "line-2" : "Nine in the second place means:\n Not going out of the gate and the courtyard\n Brings misfortune.",
    "line-3" : "Six in the third place means:\n He who knows limitation\n Will have cause to lament.\n No blame.",
    "line-4" : "Six in the fourth place means:\n Contented limitation. Success.",
    "line-5" : "Nine in the fifth place means:\n Sweet limitation brings good fortune.\n Going brings esteem.",
    "line-6" : "Six at the top means:\n Galling limitation.\n Perseverance brings misfortune.\n Remorse disappears.",
  },
  {
    "number" : "61",
    "name-interpretation" : "Inner Truth",
    "judgment" : "INNER TRUTH. Pigs and fishes.\n Good fortune.\n It furthers one to cross the great water.\n Perseverance furthers.",
    "line-1" : "Nine at the beginning means:\n Being prepared brings good fortune.\n If there are secret designs, it is disquieting.",
    "line-2" : "Nine in the second place means:\n A crane calling in the shade.\n Its young answers it.\n I have a good goblet.\n I will share it with you.",
    "line-3" : "Six in the third place means:\n He finds a comrade.\n Now he beats the drum, now he stops.\n Now he sobs, now he sings.",
    "line-4" : "Six in the fourth place means:\n The moon nearly at the full.\n The team horse goes astray.\n No blame.",
    "line-5" : "Nine in the fifth place means:\n He possesses truth, which links together.\n No blame.",
    "line-6" : "Nine at the top means:\n Cockcrow penetrating to heaven.\n Perseverance brings misfortune.",
  },
  {
    "number" : "62",
    "name-interpretation" : "Preponderance of the Small",
    "judgment" : "PREPONDERANCE OF THE SMALL. Success.\n Perseverance furthers.\n Small things may be done; great things should not be done.\n The flying bird brings the message:\n It is not well to strive upward,\n It is well to remain below.\n Great good fortune.",
    "line-1" : "Six at the beginning means:\n The bird meets with misfortune through flying.",
    "line-2" : "Six in the second place means:\n She passes by her ancestor\n And meets her ancestress.\n He does not reach his prince\n And meets the official.\n No blame.",
    "line-3" : "Nine in the third place means:\n If one is not extremely careful,\n Somebody may come up from behind and strike him.\n Misfortune.",
    "line-4" : "Nine in the fourth place means:\n No blame. He meets him without passing by.\n Going brings danger. One must be on guard.\n Do not act. Be constantly persevering.",
    "line-5" : "Six in the fifth place means:\n Dense clouds,\n No rain from our western territory.\n The prince shoots and hits him who is in the cave.",
    "line-6" : "Six at the top means:\n He passes him by, not meeting him.\n The flying bird leaves him.\n Misfortune.\n This means bad luck and injury.",
  },
  {
    "number" : "63",
    "name-interpretation" : "After Completion",
    "judgment" : "AFTER COMPLETION. Success in small matters.\n Perseverance furthers.\n At the beginning good fortune.\n At the end disorder.",
    "line-1" : "Nine at the beginning means:\n He breaks his wheels.\n He gets his tail in the water.\n No blame.",
    "line-2" : "Six in the second place means:\n The woman loses the curtain of her carriage.\n Do not run after it;\n On the seventh day you will get it.",
    "line-3" : "Nine in the third place means:\n The Illustrious Ancestor\n Disciplines the Devil's Country.\n After three years he conquers it.\n Inferior people must not be employed.",
    "line-4" : "Six in the fourth place means:\n The finest clothes turn to rags.\n Be careful all day long.",
    "line-5" : "Nine in the fifth place means:\n The neighbor in the east who slaughters an ox\n Does not attain as much real happiness\n As the neighbor in the west\n With his small offering.",
    "line-6" : "Six at the top means:\n He gets his head in the water. Danger.",
  },
  {
    "number" : "64",
    "name-interpretation" : "Before Completion",
    "judgment" : "BEFORE COMPLETION. Success.\n But if the little fox, after nearly completing the crossing,\n Gets his tail in the water,\n There is nothing that would further.",
    "line-1" : "Six at the beginning means:\n He gets his tail in the water.\n Humiliating.",
    "line-2" : "Nine in the second place means:\n He brakes his wheels.\n Perseverance brings good fortune.",
    "line-3" : "Six in the third place means:\n Before completion, attack brings misfortune.\n It furthers one to cross the great water.",
    "line-4" : "Nine in the fourth place means:\n Perseverance brings good fortune.\n Remorse disappears.\n Shock, thus to discipline the Devil's Country.\n For three years, great realms are rewarded.",
    "line-5" : "Six in the fifth place means:\n Perseverance brings good fortune.\n No remorse.\n The light of the superior man is true.\n Good fortune.",
    "line-6" : "Nine at the top means:\n There is drinking of wine\n In genuine confidence. No blame.\n But if one wets his head,\n He loses it, in truth.",
  },
]
}
}
