all: ../src/code/text-wilhelm.js ../src/code/text-wilhelm-baynes.js

../src/code/text-wilhelm.js: text-wilhelm.xml translatejs
	./translatejs text-wilhelm.xml > ../src/code/text-wilhelm.js
../src/code/text-wilhelm-baynes.js: text-wilhelm-baynes.xml translatejs
	./translatejs text-wilhelm-baynes.xml > ../src/code/text-wilhelm-baynes.js
